export type JourneyStage = 'discover' | 'research' | 'shop' | 'nurture' | 'operations' | 'export';
export type ChannelStatus = 'connected' | 'available' | 'coming-soon';
export type ChannelCategory = 
  | 'display' | 'search' | 'retail-media' | 'social-ads'
  | 'product-info' | 'reviews' | 'affiliate'
  | 'ecommerce' | 'marketplace' | 'social-commerce' | 'b2b'
  | 'email-sms' | 'loyalty' | 'support' | 'chatbot'
  | 'pim-dam' | 'erp' | 'analytics' | 'training'
  | 'data-export' | 'content-package' | 'print' | 'api';

export interface DeploymentChannel {
  id: string;
  name: string;
  logo: string; // emoji fallback
  logoUrl?: string; // actual logo URL
  brandColor: string;
  description: string;
  category: ChannelCategory;
  journeyStage: JourneyStage;
  status: ChannelStatus;
  requiresAuth: boolean;
  isPremium: boolean;
  monthlyCost?: number;
  products?: number;
  lastDeployed?: Date;
  integrationPartner?: string;
}

export const deploymentChannels: DeploymentChannel[] = [
  // DISCOVER (Awareness)
  {
    id: 'google-display',
    name: 'Google Display Network',
    logo: '🔴',
    logoUrl: 'https://cdn.simpleicons.org/google/4285F4',
    brandColor: '#4285F4',
    description: 'Reach millions with display advertising',
    category: 'display',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'meta-ads',
    name: 'Meta Ads Manager',
    logo: '📘',
    logoUrl: 'https://cdn.simpleicons.org/meta/1877F2',
    brandColor: '#1877F2',
    description: 'Facebook & Instagram advertising',
    category: 'display',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'tiktok-ads',
    name: 'TikTok Ads',
    logo: '🎵',
    logoUrl: 'https://cdn.simpleicons.org/tiktok/000000',
    brandColor: '#000000',
    description: 'Engage younger audiences with video ads',
    category: 'social-ads',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'pinterest-ads',
    name: 'Pinterest Ads',
    logo: '📌',
    logoUrl: 'https://cdn.simpleicons.org/pinterest/E60023',
    brandColor: '#E60023',
    description: 'Inspire shoppers with visual discovery',
    category: 'social-ads',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'snapchat-ads',
    name: 'Snapchat Ads',
    logo: '👻',
    logoUrl: 'https://cdn.simpleicons.org/snapchat/FFFC00',
    brandColor: '#FFFC00',
    description: 'Reach Gen Z & Millennials',
    category: 'social-ads',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'youtube-ads',
    name: 'YouTube Ads',
    logo: '▶️',
    logoUrl: 'https://cdn.simpleicons.org/youtube/FF0000',
    brandColor: '#FF0000',
    description: 'Video advertising on YouTube',
    category: 'social-ads',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'amazon-dsp',
    name: 'Amazon DSP',
    logo: '🟡',
    logoUrl: 'https://cdn.simpleicons.org/amazon/FF9900',
    brandColor: '#FF9900',
    description: 'Display ads on and off Amazon',
    category: 'retail-media',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'walmart-connect-offsite',
    name: 'Walmart Connect (Offsite)',
    logo: '⭐',
    logoUrl: 'https://cdn.simpleicons.org/walmart/0071CE',
    brandColor: '#0071CE',
    description: 'Reach shoppers off Walmart.com',
    category: 'retail-media',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'target-roundel-offsite',
    name: 'Target Roundel (Offsite)',
    logo: '🎯',
    logoUrl: 'https://cdn.simpleicons.org/target/CC0000',
    brandColor: '#CC0000',
    description: 'Target shoppers beyond Target.com',
    category: 'retail-media',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'kroger-precision',
    name: 'Kroger Precision Marketing',
    logo: '🛒',
    logoUrl: 'https://cdn.simpleicons.org/kroger/0057A4',
    brandColor: '#0057A4',
    description: 'Reach grocery shoppers',
    category: 'retail-media',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'instacart-ads',
    name: 'Instacart Ads',
    logo: '🥕',
    logoUrl: 'https://cdn.simpleicons.org/instacart/43B02A',
    brandColor: '#43B02A',
    description: 'Advertise on Instacart',
    category: 'retail-media',
    journeyStage: 'discover',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'cvs-media',
    name: 'CVS Media Exchange',
    logo: '💊',
    brandColor: '#CC0000',
    description: 'Health & wellness advertising',
    category: 'retail-media',
    journeyStage: 'discover',
    status: 'coming-soon',
    requiresAuth: true,
    isPremium: true,
  },

  // RESEARCH (Consideration)
  {
    id: 'amazon-sponsored',
    name: 'Amazon Sponsored Products',
    logo: '🟡',
    logoUrl: 'https://cdn.simpleicons.org/amazon/FF9900',
    brandColor: '#FF9900',
    description: 'Sponsored search on Amazon',
    category: 'retail-media',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'walmart-connect-search',
    name: 'Walmart Connect Search',
    logo: '⭐',
    logoUrl: 'https://cdn.simpleicons.org/walmart/0071CE',
    brandColor: '#0071CE',
    description: 'Sponsored search on Walmart',
    category: 'retail-media',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'target-roundel-search',
    name: 'Target Roundel Search',
    logo: '🎯',
    logoUrl: 'https://cdn.simpleicons.org/target/CC0000',
    brandColor: '#CC0000',
    description: 'Sponsored search on Target',
    category: 'retail-media',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'google-merchant',
    name: 'Google Merchant Center',
    logo: '🔴',
    logoUrl: 'https://cdn.simpleicons.org/google/4285F4',
    brandColor: '#4285F4',
    description: 'Product feed for Google Shopping',
    category: 'product-info',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'bing-merchant',
    name: 'Bing Merchant Center',
    logo: '🟦',
    logoUrl: 'https://cdn.simpleicons.org/bing/008373',
    brandColor: '#008373',
    description: 'Product feed for Bing Shopping',
    category: 'product-info',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'bazaarvoice',
    name: 'Bazaarvoice',
    logo: '⭐',
    logoUrl: 'https://cdn.simpleicons.org/bazaarvoice/FF6B35',
    brandColor: '#FF6B35',
    description: 'Reviews & ratings platform',
    category: 'reviews',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'yotpo',
    name: 'Yotpo Reviews',
    logo: '💬',
    logoUrl: 'https://cdn.simpleicons.org/yotpo/5B2E91',
    brandColor: '#5B2E91',
    description: 'Customer reviews & UGC',
    category: 'reviews',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'trustpilot',
    name: 'Trustpilot',
    logo: '⭐',
    logoUrl: 'https://cdn.simpleicons.org/trustpilot/00B67A',
    brandColor: '#00B67A',
    description: 'Customer review platform',
    category: 'reviews',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'commission-junction',
    name: 'Commission Junction',
    logo: '🤝',
    logoUrl: 'https://cdn.simpleicons.org/cj/0066CC',
    brandColor: '#0066CC',
    description: 'Affiliate marketing network',
    category: 'affiliate',
    journeyStage: 'research',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },

  // SHOP (Purchase)
  // E-commerce Platforms
  {
    id: 'shopify',
    name: 'Shopify',
    logo: '🔷',
    logoUrl: 'https://cdn.simpleicons.org/shopify/96BF48',
    brandColor: '#96BF48',
    description: 'Leading e-commerce platform',
    category: 'ecommerce',
    journeyStage: 'shop',
    status: 'connected',
    requiresAuth: true,
    isPremium: false,
    products: 3,
  },
  {
    id: 'magento',
    name: 'Magento / Adobe Commerce',
    logo: '🟠',
    logoUrl: 'https://cdn.simpleicons.org/magento/EE672F',
    brandColor: '#EE672F',
    description: 'Enterprise e-commerce platform',
    category: 'ecommerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'bigcommerce',
    name: 'BigCommerce',
    logo: '🔵',
    logoUrl: 'https://cdn.simpleicons.org/bigcommerce/121118',
    brandColor: '#121118',
    description: 'Scalable e-commerce platform',
    category: 'ecommerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    logo: '🟣',
    logoUrl: 'https://cdn.simpleicons.org/woocommerce/96588A',
    brandColor: '#96588A',
    description: 'WordPress e-commerce plugin',
    category: 'ecommerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'salesforce-commerce',
    name: 'Salesforce Commerce Cloud',
    logo: '☁️',
    logoUrl: 'https://cdn.simpleicons.org/salesforce/00A1E0',
    brandColor: '#00A1E0',
    description: 'Enterprise commerce solution',
    category: 'ecommerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'sap-commerce',
    name: 'SAP Commerce Cloud',
    logo: '🔷',
    logoUrl: 'https://cdn.simpleicons.org/sap/0FAAFF',
    brandColor: '#0FAAFF',
    description: 'Enterprise commerce platform',
    category: 'ecommerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },

  // Marketplaces
  {
    id: 'amazon-seller',
    name: 'Amazon Seller Central',
    logo: '🟡',
    logoUrl: 'https://cdn.simpleicons.org/amazon/FF9900',
    brandColor: '#FF9900',
    description: 'World\'s largest marketplace',
    category: 'marketplace',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'walmart-marketplace',
    name: 'Walmart Marketplace',
    logo: '⭐',
    logoUrl: 'https://cdn.simpleicons.org/walmart/0071CE',
    brandColor: '#0071CE',
    description: 'Major retail marketplace',
    category: 'marketplace',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'target-plus',
    name: 'Target+',
    logo: '🎯',
    logoUrl: 'https://cdn.simpleicons.org/target/CC0000',
    brandColor: '#CC0000',
    description: 'Target marketplace',
    category: 'marketplace',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'ebay',
    name: 'eBay',
    logo: '🟢',
    logoUrl: 'https://cdn.simpleicons.org/ebay/E53238',
    brandColor: '#E53238',
    description: 'Global marketplace',
    category: 'marketplace',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'etsy',
    name: 'Etsy',
    logo: '🟠',
    logoUrl: 'https://cdn.simpleicons.org/etsy/F56400',
    brandColor: '#F56400',
    description: 'Handmade & vintage marketplace',
    category: 'marketplace',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'wayfair',
    name: 'Wayfair',
    logo: '🏠',
    logoUrl: 'https://cdn.simpleicons.org/wayfair/7C2579',
    brandColor: '#7C2579',
    description: 'Home goods marketplace',
    category: 'marketplace',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'bestbuy-marketplace',
    name: 'Best Buy Marketplace',
    logo: '🔵',
    logoUrl: 'https://cdn.simpleicons.org/bestbuy/0046BE',
    brandColor: '#0046BE',
    description: 'Electronics marketplace',
    category: 'marketplace',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'newegg',
    name: 'Newegg',
    logo: '🥚',
    logoUrl: 'https://cdn.simpleicons.org/newegg/F75F00',
    brandColor: '#F75F00',
    description: 'Tech & electronics marketplace',
    category: 'marketplace',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },

  // Social Commerce
  {
    id: 'instagram-shopping',
    name: 'Instagram Shopping',
    logo: '📷',
    logoUrl: 'https://cdn.simpleicons.org/instagram/E4405F',
    brandColor: '#E4405F',
    description: 'Shop directly on Instagram',
    category: 'social-commerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'facebook-shops',
    name: 'Facebook Shops',
    logo: '💬',
    logoUrl: 'https://cdn.simpleicons.org/facebook/1877F2',
    brandColor: '#1877F2',
    description: 'Sell on Facebook',
    category: 'social-commerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'tiktok-shop',
    name: 'TikTok Shop',
    logo: '🎵',
    logoUrl: 'https://cdn.simpleicons.org/tiktok/000000',
    brandColor: '#000000',
    description: 'Live shopping on TikTok',
    category: 'social-commerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'pinterest-shopping',
    name: 'Pinterest Shopping',
    logo: '📌',
    logoUrl: 'https://cdn.simpleicons.org/pinterest/E60023',
    brandColor: '#E60023',
    description: 'Shoppable pins',
    category: 'social-commerce',
    journeyStage: 'shop',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },

  // NURTURE (Engagement)
  // Email/SMS
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    logo: '📧',
    logoUrl: 'https://cdn.simpleicons.org/klaviyo/F37E42',
    brandColor: '#F37E42',
    description: 'E-commerce email & SMS marketing',
    category: 'email-sms',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    logo: '🐒',
    logoUrl: 'https://cdn.simpleicons.org/mailchimp/FFE01B',
    brandColor: '#FFE01B',
    description: 'Email marketing platform',
    category: 'email-sms',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'salesforce-marketing',
    name: 'Salesforce Marketing Cloud',
    logo: '☁️',
    logoUrl: 'https://cdn.simpleicons.org/salesforce/00A1E0',
    brandColor: '#00A1E0',
    description: 'Enterprise marketing automation',
    category: 'email-sms',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    logo: '🟠',
    logoUrl: 'https://cdn.simpleicons.org/hubspot/FF7A59',
    brandColor: '#FF7A59',
    description: 'Marketing & CRM platform',
    category: 'email-sms',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'attentive',
    name: 'Attentive',
    logo: '📱',
    logoUrl: 'https://cdn.simpleicons.org/attentive/FF5A5F',
    brandColor: '#FF5A5F',
    description: 'SMS marketing for e-commerce',
    category: 'email-sms',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },

  // Support
  {
    id: 'zendesk',
    name: 'Zendesk',
    logo: '💬',
    logoUrl: 'https://cdn.simpleicons.org/zendesk/03363D',
    brandColor: '#03363D',
    description: 'Customer support platform',
    category: 'support',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'intercom',
    name: 'Intercom',
    logo: '⚡',
    logoUrl: 'https://cdn.simpleicons.org/intercom/1F8DED',
    brandColor: '#1F8DED',
    description: 'Customer messaging platform',
    category: 'support',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'gorgias',
    name: 'Gorgias',
    logo: '💎',
    logoUrl: 'https://cdn.simpleicons.org/gorgias/222222',
    brandColor: '#222222',
    description: 'E-commerce helpdesk',
    category: 'support',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    logo: '🍋',
    logoUrl: 'https://cdn.simpleicons.org/freshdesk/3AB0FF',
    brandColor: '#3AB0FF',
    description: 'Customer support software',
    category: 'support',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },

  // Chatbot/AI
  {
    id: 'chatbot-training',
    name: 'Chatbot Training Data',
    logo: '🤖',
    brandColor: '#667EEA',
    description: 'Export for AI chatbot training',
    category: 'chatbot',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },
  {
    id: 'voice-assistant',
    name: 'Voice Assistant Content',
    logo: '🎙️',
    brandColor: '#48BB78',
    description: 'Content for voice shopping',
    category: 'chatbot',
    journeyStage: 'nurture',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },

  // OPERATIONS (Internal)
  // PIM/DAM
  {
    id: 'salsify',
    name: 'Salsify',
    logo: '🟢',
    logoUrl: 'https://cdn.simpleicons.org/salsify/00B140',
    brandColor: '#00B140',
    description: 'Product experience management',
    category: 'pim-dam',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'akeneo',
    name: 'Akeneo',
    logo: '🟣',
    logoUrl: 'https://cdn.simpleicons.org/akeneo/9452BA',
    brandColor: '#9452BA',
    description: 'Open-source PIM',
    category: 'pim-dam',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'inriver',
    name: 'inRiver',
    logo: '🔵',
    logoUrl: 'https://cdn.simpleicons.org/inriver/0066CC',
    brandColor: '#0066CC',
    description: 'Enterprise PIM solution',
    category: 'pim-dam',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'syndigo',
    name: 'Syndigo',
    logo: '🟠',
    logoUrl: 'https://cdn.simpleicons.org/syndigo/FF6B35',
    brandColor: '#FF6B35',
    description: 'Content syndication network',
    category: 'pim-dam',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'bynder',
    name: 'Bynder',
    logo: '🎨',
    logoUrl: 'https://cdn.simpleicons.org/bynder/4FC2F7',
    brandColor: '#4FC2F7',
    description: 'Digital asset management',
    category: 'pim-dam',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },

  // ERP
  {
    id: 'netsuite',
    name: 'NetSuite',
    logo: '☁️',
    logoUrl: 'https://cdn.simpleicons.org/oracle/FF6600',
    brandColor: '#FF6600',
    description: 'Cloud ERP system',
    category: 'erp',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
  {
    id: 'sap-erp',
    name: 'SAP ERP',
    logo: '🔷',
    logoUrl: 'https://cdn.simpleicons.org/sap/0FAAFF',
    brandColor: '#0FAAFF',
    description: 'Enterprise resource planning',
    category: 'erp',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },

  // Analytics
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    logo: '📊',
    logoUrl: 'https://cdn.simpleicons.org/googleanalytics/E37400',
    brandColor: '#E37400',
    description: 'Web analytics platform',
    category: 'analytics',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: false,
  },
  {
    id: 'tableau',
    name: 'Tableau',
    logo: '📈',
    logoUrl: 'https://cdn.simpleicons.org/tableau/E97627',
    brandColor: '#E97627',
    description: 'Business intelligence',
    category: 'analytics',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },

  // Training
  {
    id: 'staff-training',
    name: 'Staff Training Modules',
    logo: '👥',
    brandColor: '#805AD5',
    description: 'Product knowledge training',
    category: 'training',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },
  {
    id: 'sales-playbook',
    name: 'Sales Playbook',
    logo: '📖',
    brandColor: '#38B2AC',
    description: 'Sales enablement content',
    category: 'training',
    journeyStage: 'operations',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },

  // EXPORT (Flexibility)
  {
    id: 'csv-export',
    name: 'CSV Export',
    logo: '📄',
    brandColor: '#718096',
    description: 'Export all products to CSV',
    category: 'data-export',
    journeyStage: 'export',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },
  {
    id: 'excel-export',
    name: 'Excel Workbook',
    logo: '📊',
    logoUrl: 'https://cdn.simpleicons.org/microsoftexcel/217346',
    brandColor: '#217346',
    description: 'Multi-sheet Excel export',
    category: 'data-export',
    journeyStage: 'export',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },
  {
    id: 'json-export',
    name: 'JSON Feed',
    logo: '⚙️',
    logoUrl: 'https://cdn.simpleicons.org/json/4A5568',
    brandColor: '#4A5568',
    description: 'API-ready JSON format',
    category: 'data-export',
    journeyStage: 'export',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },
  {
    id: 'xml-export',
    name: 'XML Feed',
    logo: '📝',
    brandColor: '#2D3748',
    description: 'Syndication XML format',
    category: 'data-export',
    journeyStage: 'export',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },
  {
    id: 'marketing-kit',
    name: 'Product Marketing Kit',
    logo: '📦',
    brandColor: '#ED8936',
    description: 'Complete marketing package (ZIP)',
    category: 'content-package',
    journeyStage: 'export',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },
  {
    id: 'print-catalog',
    name: 'Print Catalog PDF',
    logo: '📖',
    brandColor: '#E53E3E',
    description: 'Print-ready product catalog',
    category: 'print',
    journeyStage: 'export',
    status: 'available',
    requiresAuth: false,
    isPremium: false,
  },
  {
    id: 'rest-api',
    name: 'REST API Access',
    logo: '🔌',
    brandColor: '#319795',
    description: 'Direct API access to content',
    category: 'api',
    journeyStage: 'export',
    status: 'available',
    requiresAuth: true,
    isPremium: true,
  },
];

export const getChannelsByStage = (stage: JourneyStage) => {
  return deploymentChannels.filter(channel => channel.journeyStage === stage);
};

export const getChannelsByCategory = (category: ChannelCategory) => {
  return deploymentChannels.filter(channel => channel.category === category);
};

export const getCategoryDisplayName = (category: ChannelCategory): string => {
  const names: Record<ChannelCategory, string> = {
    'display': 'Display Advertising',
    'search': 'Search & Shopping',
    'retail-media': 'Retail Media Networks',
    'social-ads': 'Social Advertising',
    'product-info': 'Product Information',
    'reviews': 'Reviews & Ratings',
    'affiliate': 'Affiliate Networks',
    'ecommerce': 'E-commerce Platforms',
    'marketplace': 'Marketplaces',
    'social-commerce': 'Social Commerce',
    'b2b': 'B2B Platforms',
    'email-sms': 'Email & SMS',
    'loyalty': 'Loyalty Programs',
    'support': 'Customer Support',
    'chatbot': 'AI & Chatbots',
    'pim-dam': 'PIM & DAM',
    'erp': 'ERP & Inventory',
    'analytics': 'Analytics',
    'training': 'Staff Training',
    'data-export': 'Data Formats',
    'content-package': 'Content Packages',
    'print': 'Print Materials',
    'api': 'API Access',
  };
  return names[category];
};
