
import { Search, MessageSquare, Users, TrendingUp, Globe, Hash, Brain, BarChart3, ShoppingCart, MapPin, Heart, AlertTriangle, Zap, Target, Quote, Globe2, MessageCircle, Video, FileText, Leaf, Link2, DollarSign, AlertCircle, HelpCircle, Store, Image, Sparkles } from 'lucide-react';

export const enrichmentFields = [
  {
    key: 'searchTrends',
    title: 'Search Intelligence',
    icon: Search,
    description: 'Popular search terms and volume data',
  },
  {
    key: 'seoKeywordVolume',
    title: 'SEO Keyword Volume',
    icon: BarChart3,
    description: 'Search volume data for targeted keywords',
  },
  {
    key: 'customerSentiment',
    title: 'Customer Sentiment Analysis',
    icon: MessageSquare,
    description: 'Insights from customer reviews and feedback',
  },
  {
    key: 'reasonsToBuy',
    title: 'Reasons to Buy',
    icon: ShoppingCart,
    description: 'Aggregated purchase motivators ranked by confidence',
  },
  {
    key: 'socialMentions',
    title: 'Social Media Intelligence',
    icon: Users,
    description: 'Social platform mentions and sentiment',
  },
  {
    key: 'verbatimQuotes',
    title: 'Verbatim Quotes & Reviews',
    icon: Quote,
    description: 'Direct quotes from social media and review sites with sources',
  },
  {
    key: 'categoryEntryPoints',
    title: 'Category Entry Points',
    icon: MapPin,
    description: 'Consumer buying situations and triggers that prompt consideration',
  },
  {
    key: 'favouriteFeatures',
    title: 'Favourite Features',
    icon: Heart,
    description: 'Most valued features ranked by confidence percentage',
  },
  {
    key: 'missingFeatures',
    title: 'Missing Features',
    icon: AlertTriangle,
    description: 'Identified feature gaps ranked by confidence percentage',
  },
  {
    key: 'competitorAnalysis',
    title: 'Competitive Landscape',
    icon: TrendingUp,
    description: 'Direct competitor analysis and positioning',
  },
  {
    key: 'keyCompetitors',
    title: 'Key Competitors',
    icon: Target,
    description: 'Primary competing products and their positioning',
  },
  {
    key: 'relativeStrengths',
    title: 'Relative Strengths',
    icon: Zap,
    description: 'Competitive advantages vs key competitors',
  },
  {
    key: 'seoOpportunities',
    title: 'SEO Opportunities',
    icon: Globe,
    description: 'High-value keyword opportunities',
  },
  {
    key: 'targetAudience',
    title: 'Target Audience Intelligence',
    icon: Hash,
    description: 'Data-driven audience segmentation',
  },
  {
    key: 'keyFeatures',
    title: 'Feature Priority Intelligence',
    icon: Brain,
    description: 'Intelligence-driven feature importance ranking',
  },
  {
    key: 'culturalInsights',
    title: 'Cultural Insights',
    icon: Globe2,
    description: 'Regional preferences and cultural buying patterns',
  },
  {
    key: 'regionalPreferences',
    title: 'Regional Preferences',
    icon: MapPin,
    description: 'Market-specific preferences and terminology',
  },
  {
    key: 'complianceData',
    title: 'Compliance & Certifications',
    icon: AlertCircle,
    description: 'Regional compliance requirements and certifications',
  },
  {
    key: 'forumDiscussions',
    title: 'Forum Discussions',
    icon: MessageCircle,
    description: 'Insights from Reddit and specialized forums',
  },
  {
    key: 'communityInsights',
    title: 'Community Insights',
    icon: Users,
    description: 'Community sentiment and problem-solving patterns',
  },
  {
    key: 'influencerReviews',
    title: 'Influencer Reviews',
    icon: Video,
    description: 'YouTube and creator content analysis',
  },
  {
    key: 'creatorContent',
    title: 'Creator Content',
    icon: Video,
    description: 'Unboxing videos and first impressions',
  },
  {
    key: 'videoSentiment',
    title: 'Video Sentiment',
    icon: Heart,
    description: 'Aggregated video content sentiment',
  },
  {
    key: 'technicalSpecs',
    title: 'Technical Specifications',
    icon: FileText,
    description: 'Detailed technical specifications and data sheets',
  },
  {
    key: 'performanceBenchmarks',
    title: 'Performance Benchmarks',
    icon: BarChart3,
    description: 'Performance metrics and standards compliance',
  },
  {
    key: 'sustainabilityScore',
    title: 'Sustainability Score',
    icon: Leaf,
    description: 'Environmental impact assessment',
  },
  {
    key: 'environmentalImpact',
    title: 'Environmental Impact',
    icon: Leaf,
    description: 'Manufacturing practices and materials analysis',
  },
  {
    key: 'compatibleProducts',
    title: 'Compatible Products',
    icon: Link2,
    description: 'Ecosystem integration and accessories',
  },
  {
    key: 'ecosystemFit',
    title: 'Ecosystem Fit',
    icon: Link2,
    description: 'Cross-sell opportunities and bundle potential',
  },
  {
    key: 'priceHistory',
    title: 'Price History',
    icon: DollarSign,
    description: 'Historical pricing trends and patterns',
  },
  {
    key: 'valuePositioning',
    title: 'Value Positioning',
    icon: DollarSign,
    description: 'Competitive price positioning and value perception',
  },
  {
    key: 'criticalReviews',
    title: 'Critical Reviews',
    icon: AlertTriangle,
    description: 'Common complaints and product weaknesses',
  },
  {
    key: 'featureRequests',
    title: 'Feature Requests',
    icon: Sparkles,
    description: 'Customer-requested features and improvements',
  },
  {
    key: 'qaInsights',
    title: 'Q&A Insights',
    icon: HelpCircle,
    description: 'Customer questions and concerns',
  },
  {
    key: 'categoryUseCases',
    title: 'Category Use Cases',
    icon: Target,
    description: 'Real-world product applications and scenarios',
  },
  {
    key: 'retailerIntelligence',
    title: 'Retailer Intelligence',
    icon: Store,
    description: 'Retailer-specific data and merchandising insights',
  },
  {
    key: 'visualPerformance',
    title: 'Visual Performance',
    icon: Image,
    description: 'Product imagery and visual content effectiveness',
  },
  {
    key: 'expertReviewComparisons',
    title: 'Expert Review Comparisons',
    icon: BarChart3,
    description: 'Professional review comparisons and ratings',
  },
  {
    key: 'innovationGaps',
    title: 'Innovation Gaps',
    icon: Sparkles,
    description: 'Feature gaps and innovation opportunities',
  },
] as const;
