import { 
  TrendingUp, 
  Award, 
  Target,
  Briefcase,
  GitCompare,
  DollarSign,
  Shield,
  Cpu,
  Sparkles,
  Layers,
  ArrowRight,
  Clock,
  Gem,
  Lock,
  MapPin,
  Unlock,
  Brain,
  BarChart,
  Zap,
  CheckCircle,
  Bell
} from 'lucide-react';
import { LadderFramework } from '@/types/ladderTypes';

export const ladderFrameworks: LadderFramework[] = [
  {
    id: 'functional-emotional',
    name: 'Functional-Emotional Ladder',
    description: 'Classic progression from tangible features to emotional outcomes and life transformation',
    explainer: 'Feature → Functional Benefit → Emotional Benefit → Life Outcome',
    bestUse: 'Consumer products where emotional connection drives purchase (automotive, lifestyle, personal care)',
    steps: ['Feature', 'Functional Benefit', 'Emotional Benefit', 'Life Outcome'],
    icon: TrendingUp,
    category: 'emotional',
    complexity: 'simple',
    exampleBrands: ['Volvo (safety → peace of mind)', 'Apple (design → confidence)', 'Nike (performance → achievement)'],
    realWorldExample: 'Volvo\'s safety features → Protects family from accidents → Peace of mind for parents → Confidence to drive anywhere'
  },
  {
    id: 'rtb',
    name: 'Reason-to-Believe',
    description: 'Build credibility through proof, then make a promise that delivers a payoff',
    explainer: 'Reason to Believe → Promise → Payoff',
    bestUse: 'Premium brands, skeptical audiences, credibility-focused positioning',
    steps: ['Reason to Believe (Proof)', 'Promise', 'Payoff'],
    icon: Award,
    category: 'trust',
    complexity: 'simple',
    exampleBrands: ['Rolls-Royce (engineering proof)', 'Michelin (testing standards)', 'Patagonia (certifications)'],
    realWorldExample: 'Rolls-Royce: "At 60mph, the loudest noise is the clock" (proof) → Unparalleled refinement (promise) → Ultimate luxury experience (payoff)'
  },
  {
    id: 'jtbd-outcome',
    name: 'Jobs-to-Be-Done Outcome',
    description: 'Focus on the progress customers try to make and constraints they need removed',
    explainer: 'Job to Be Done → Outcome → Constraint Removed → Progress Made',
    bestUse: 'Product innovation, market disruption, understanding true competition',
    steps: ['Job to Be Done', 'Desired Outcome', 'Constraint Removed', 'Progress Made'],
    icon: Target,
    category: 'functional',
    complexity: 'moderate',
    exampleBrands: ['Airbnb (belong anywhere)', 'Uber (reliable ride)', 'Slack (team communication)'],
    realWorldExample: 'Airbnb: Need accommodation (job) → Feel at home anywhere (outcome) → Remove hotel impersonality (constraint) → Travel like a local (progress)'
  },
  {
    id: 'faai',
    name: 'Feature-Advantage-Application-Impact',
    description: 'B2B ladder linking technical features to business outcomes',
    explainer: 'Feature → Advantage → Application → Business Impact',
    bestUse: 'B2B sales, enterprise software, industrial equipment',
    steps: ['Feature', 'Advantage', 'Application', 'Business Impact'],
    icon: Briefcase,
    category: 'functional',
    complexity: 'moderate',
    exampleBrands: ['Salesforce (CRM features → revenue growth)', 'SAP (ERP efficiency)', 'AWS (scalability → cost savings)'],
    realWorldExample: 'Salesforce: 360° customer view (feature) → Complete data access (advantage) → Sales team closes faster (application) → 37% revenue increase (impact)'
  },
  {
    id: 'cabo',
    name: 'Category-Attribute-Benefit-Outcome',
    description: 'Position against category norms by highlighting key differentiating attributes',
    explainer: 'Category → Key Attribute → Benefit → Ultimate Outcome',
    bestUse: 'Competitive positioning, category disruption, differentiation',
    steps: ['Category Context', 'Key Attribute', 'Functional Benefit', 'Ultimate Outcome'],
    icon: GitCompare,
    category: 'value',
    complexity: 'moderate',
    exampleBrands: ['Tesla (electric vs gas)', 'Dyson (bagless vacuum)', 'Purple Mattress (grid tech)'],
    realWorldExample: 'Tesla: EVs (category) → Instant torque (attribute) → Fastest acceleration (benefit) → Redefine driving experience (outcome)'
  },
  {
    id: 'price-value-roi',
    name: 'Price-Cost-Value-ROI Ladder',
    description: 'Financial justification from price point to return on investment',
    explainer: 'Price → True Cost → Value Delivered → ROI',
    bestUse: 'Premium pricing justification, B2B purchasing, enterprise sales',
    steps: ['Price', 'True Cost', 'Value', 'ROI'],
    icon: DollarSign,
    category: 'value',
    complexity: 'moderate',
    exampleBrands: ['Salesforce (subscription ROI)', 'Apple (ecosystem value)', 'Costco (membership value)'],
    realWorldExample: 'Salesforce: $150/user/mo (price) → Replaces 5 tools at $300/mo (cost) → 37% faster sales (value) → $500K annual revenue increase (ROI)'
  },
  {
    id: 'risk-mitigation',
    name: 'Risk-Mitigation-Confidence-Action',
    description: 'Remove barriers by addressing risks and building confidence',
    explainer: 'Risk → Mitigation → Confidence → Action',
    bestUse: 'High-consideration purchases, financial services, healthcare',
    steps: ['Identified Risk', 'Mitigation Strategy', 'Confidence Builder', 'Purchase Action'],
    icon: Shield,
    category: 'trust',
    complexity: 'simple',
    exampleBrands: ['Zappos (free returns)', 'Warby Parker (home try-on)', 'Coinbase (security measures)'],
    realWorldExample: 'Coinbase: Losing crypto to hacks (risk) → 98% cold storage (mitigation) → Peace of mind (confidence) → Invest with certainty (action)'
  },
  {
    id: 'component-performance',
    name: 'Component-Performance-Capability',
    description: 'Technical progression from parts to system-level capabilities',
    explainer: 'Component → Performance → Capability → Outcome',
    bestUse: 'Technical products, engineering-focused audiences, B2B industrial',
    steps: ['Component/Tech', 'Performance Metric', 'Capability', 'Real-World Outcome'],
    icon: Cpu,
    category: 'functional',
    complexity: 'advanced',
    exampleBrands: ['Porsche (PCCB brakes)', 'Intel (processor specs)', 'Gore-Tex (membrane tech)'],
    realWorldExample: 'Porsche PCCB: Carbon-ceramic disc (component) → 40% lighter, fade-resistant (performance) → Shorter stopping distance (capability) → Track-ready confidence (outcome)'
  },
  {
    id: 'experience',
    name: 'Experience Ladder',
    description: 'From product to function to memorable experience',
    explainer: 'Product → Function → Experience → Memory',
    bestUse: 'Experience-driven brands, hospitality, entertainment, luxury',
    steps: ['Product', 'Function', 'Experience', 'Lasting Memory'],
    icon: Sparkles,
    category: 'experience',
    complexity: 'moderate',
    exampleBrands: ['Disney (parks)', 'Apple Store', 'Ritz-Carlton', 'GoPro'],
    realWorldExample: 'Disney Parks: Rides & shows (product) → Entertainment (function) → Magical immersion (experience) → Cherished family memories (memory)'
  },
  {
    id: 'value-stack',
    name: 'Value Stack',
    description: 'Compounding value from utility to ecosystem to competitive moat',
    explainer: 'Utility → Multiplier → Ecosystem → Moat',
    bestUse: 'Platform businesses, SaaS products, network effects',
    steps: ['Base Utility', 'Value Multiplier', 'Ecosystem', 'Competitive Moat'],
    icon: Layers,
    category: 'value',
    complexity: 'advanced',
    exampleBrands: ['Amazon (marketplace)', 'Salesforce (AppExchange)', 'Apple (ecosystem)', 'Shopify'],
    realWorldExample: 'Amazon: Buy products (utility) → Prime fast shipping (multiplier) → Marketplace + AWS + Devices (ecosystem) → Switching cost moat (moat)'
  },
  {
    id: 'funnel',
    name: 'Awareness-Consideration-Conversion',
    description: 'Align messaging to buyer journey stages',
    explainer: 'Awareness → Consideration → Conversion → Retention',
    bestUse: 'Marketing campaigns, content strategy, funnel optimization',
    steps: ['Awareness Hook', 'Consideration Factor', 'Conversion Trigger', 'Retention Driver'],
    icon: ArrowRight,
    category: 'experience',
    complexity: 'simple',
    exampleBrands: ['HubSpot (inbound funnel)', 'Mailchimp (email journey)', 'Shopify (merchant funnel)'],
    realWorldExample: 'HubSpot: Free tools (awareness) → Compare features (consideration) → Free trial (conversion) → Expansion revenue (retention)'
  },
  {
    id: 'temporal',
    name: 'Before-During-After-Impact',
    description: 'Temporal transformation showing the journey',
    explainer: 'Before State → During Experience → After Result → Long-Term Impact',
    bestUse: 'Transformation stories, weight loss, education, career development',
    steps: ['Before', 'During', 'After', 'Long-Term Impact'],
    icon: Clock,
    category: 'experience',
    complexity: 'simple',
    exampleBrands: ['Weight Watchers', 'Coursera', 'LinkedIn Learning', 'Peloton'],
    realWorldExample: 'Peloton: Out of shape (before) → Fun workouts at home (during) → Lost 30 lbs (after) → Sustained healthy lifestyle (impact)'
  },
  {
    id: 'compounding',
    name: 'Micro-Feature Compounding',
    description: 'Show how small features add up to exponential value',
    explainer: 'Micro-Features → Micro-Benefits → Compounding Value → Exponential Outcome',
    bestUse: 'Multi-feature products, Swiss Army Knife positioning, all-in-one tools',
    steps: ['Micro-Features', 'Individual Benefits', 'Compounding Value', 'Exponential Outcome'],
    icon: Gem,
    category: 'value',
    complexity: 'moderate',
    exampleBrands: ['iPhone (replaces 10 devices)', 'Notion (all-in-one workspace)', 'Swiss Army Knife'],
    realWorldExample: 'iPhone: Camera + GPS + Music + Browser + Phone (features) → Each solves a need (benefits) → Replaces 10 devices (compounding) → Digital life in pocket (outcome)'
  },
  {
    id: 'asset-trust',
    name: 'Asset Trust Ladder',
    description: 'Build trust through proven accuracy, reliability, and predictability',
    explainer: 'Accuracy → Reliability → Predictability → Confidence → Action',
    bestUse: 'Financial services, data platforms, critical infrastructure, healthcare',
    steps: ['Accuracy', 'Reliability', 'Predictability', 'Confidence', 'Action'],
    icon: Lock,
    category: 'trust',
    complexity: 'moderate',
    exampleBrands: ['Coinbase (crypto security)', 'Bloomberg Terminal (data accuracy)', 'AWS (uptime)'],
    realWorldExample: 'Coinbase: 98% cold storage (accuracy) → Zero hacks to date (reliability) → Consistent security (predictability) → Peace of mind (confidence) → Invest freely (action)'
  },
  {
    id: 'category-entry-points',
    name: 'Category Entry Points (CEPs)',
    description: 'Identify buying situations and mental availability triggers that make your brand come to mind',
    explainer: 'Buying Situation → Category Cue → Brand Association → Mental Availability',
    bestUse: 'Brand building, marketing strategy, understanding when customers think of your category',
    steps: ['Buying Situation', 'Category Cue', 'Brand Association', 'Mental Availability'],
    icon: MapPin,
    category: 'experience',
    complexity: 'moderate',
    exampleBrands: ['Red Bull (energy need)', 'Uber (need a ride)', 'Spotify (want music)'],
    realWorldExample: 'Red Bull: Feeling tired at 3pm (situation) → Need energy boost (cue) → Wings/extreme sports (association) → Red Bull comes to mind (availability)'
  },
  {
    id: 'purchase-barriers',
    name: 'Purchase Barriers + Solutions',
    description: 'Systematically identify and remove obstacles preventing purchase decisions',
    explainer: 'Barrier Identified → Solution Offered → Objection Handled → Path Cleared',
    bestUse: 'Conversion optimization, sales enablement, reducing purchase friction',
    steps: ['Barrier Identified', 'Solution Offered', 'Objection Handled', 'Path Cleared'],
    icon: Unlock,
    category: 'trust',
    complexity: 'simple',
    exampleBrands: ['Warby Parker (home try-on)', 'Zappos (free returns)', 'Casper (100-night trial)'],
    realWorldExample: 'Warby Parker: Can\'t try glasses online (barrier) → Home try-on program (solution) → Risk-free testing (objection handled) → Confident online purchase (cleared)'
  },
  {
    id: 'memory-structures',
    name: 'Distinctive Memory Structures',
    description: 'Build unique brand assets that create instant recall and distinctive brand codes',
    explainer: 'Distinctive Asset → Sensory Trigger → Memory Association → Instant Recognition',
    bestUse: 'Brand building, distinctive assets, creating memorable brand codes',
    steps: ['Distinctive Asset', 'Sensory Trigger', 'Memory Association', 'Instant Recognition'],
    icon: Brain,
    category: 'experience',
    complexity: 'advanced',
    exampleBrands: ['McDonald\'s (Golden Arches)', 'Intel (bong sound)', 'Tiffany (blue box)'],
    realWorldExample: 'Tiffany: Blue box (asset) → Specific Pantone color (trigger) → Luxury & romance (association) → Instant brand recognition (recall)'
  },
  {
    id: 'behavioral-economics',
    name: 'Behavioural Economics Arsenal',
    description: 'Apply proven psychological principles and cognitive biases to influence decisions',
    explainer: 'Bias Identified → Principle Applied → Behavior Nudged → Decision Made',
    bestUse: 'Conversion optimization, pricing strategy, marketing psychology',
    steps: ['Bias Identified', 'Principle Applied', 'Behavior Nudged', 'Decision Made'],
    icon: BarChart,
    category: 'value',
    complexity: 'advanced',
    exampleBrands: ['Amazon (scarcity)', 'Booking.com (social proof)', 'Netflix (default choice)'],
    realWorldExample: 'Booking.com: Loss aversion bias (identified) → "Only 1 room left!" (applied) → Urgency created (nudged) → Book now (decision)'
  },
  {
    id: 'competitive-moats',
    name: 'Competitive Moats',
    description: 'Build sustainable competitive advantages that are difficult for competitors to replicate',
    explainer: 'Competitive Threat → Defensive Moat → Sustainable Advantage → Market Leadership',
    bestUse: 'Strategic positioning, long-term differentiation, defendable market position',
    steps: ['Competitive Threat', 'Defensive Moat', 'Sustainable Advantage', 'Market Leadership'],
    icon: Shield,
    category: 'value',
    complexity: 'advanced',
    exampleBrands: ['Apple (ecosystem)', 'Amazon (logistics network)', 'Coca-Cola (brand equity)'],
    realWorldExample: 'Apple: Easy to switch devices (threat) → Seamless ecosystem integration (moat) → Switching costs too high (advantage) → Dominant market position (leadership)'
  },
  {
    id: 'conversion-mechanics',
    name: 'Conversion Mechanics',
    description: 'Optimize decision-making moments with specific techniques that drive immediate action',
    explainer: 'Decision Point → Friction Removed → Incentive Applied → Conversion Achieved',
    bestUse: 'E-commerce optimization, landing pages, checkout flows, sales enablement',
    steps: ['Decision Point', 'Friction Removed', 'Incentive Applied', 'Conversion Achieved'],
    icon: CheckCircle,
    category: 'experience',
    complexity: 'simple',
    exampleBrands: ['Amazon (1-Click)', 'Shopify (instant checkout)', 'Stripe (embedded payments)'],
    realWorldExample: 'Amazon: Ready to buy (point) → 1-Click ordering (friction removed) → Prime free shipping (incentive) → Purchase complete (conversion)'
  },
  {
    id: 'context-triggers',
    name: 'Context Triggers',
    description: 'Identify specific moments and contexts when your brand becomes highly relevant',
    explainer: 'Context/Moment → Need Activated → Brand Recalled → Action Triggered',
    bestUse: 'Marketing timing, contextual advertising, moment-based marketing',
    steps: ['Context/Moment', 'Need Activated', 'Brand Recalled', 'Action Triggered'],
    icon: Bell,
    category: 'experience',
    complexity: 'moderate',
    exampleBrands: ['Gatorade (sports)', 'Uber Eats (dinner time)', 'LinkedIn (career moments)'],
    realWorldExample: 'LinkedIn: Job change moment (context) → Need to update profile (activated) → LinkedIn is career platform (recalled) → Log in and update (triggered)'
  },
  {
    id: 'persuasion-stack',
    name: 'The Persuasion Stack',
    description: 'Layer multiple persuasion techniques for compounding effect and maximum influence',
    explainer: 'Foundation (Logic) → Emotion Layer → Social Proof Layer → Urgency Peak',
    bestUse: 'Complex sales, high-consideration purchases, comprehensive marketing campaigns',
    steps: ['Foundation (Logic)', 'Emotion Layer', 'Social Proof Layer', 'Urgency Peak'],
    icon: Layers,
    category: 'emotional',
    complexity: 'advanced',
    exampleBrands: ['Tesla (logic + emotion + social + scarcity)', 'Apple launches', 'Supreme drops'],
    realWorldExample: 'Tesla: Superior tech specs (logic) → Environmental mission (emotion) → Celebrity owners (social proof) → Limited production (urgency) → Waitlist signup'
  }
];
