
import { Asset } from '@/types/asset';

export const generateSampleAssets = (): Asset[] => {
  const assets: Asset[] = [
    // Product 1: CD1234 - TechSound Headphones
    {
      id: 1,
      sku: 'CD1234',
      name: 'CD1234 24 Hour Charge Wireless Headphones | Bluetooth 5.0 | Foldable | Mic',
      category: 'Electronics > Audio > Headphones',
      brand: 'TechSound',
      status: 'Enhanced',
      quality: 95,
      price: '$189.99',
      description: 'Premium wireless headphones with 24-hour battery life, Bluetooth 5.0 connectivity, foldable design and built-in microphone for calls',
      features: 'Bluetooth 5.0, 24-hour battery, Foldable design, Built-in microphone, Active noise cancellation',
      targetAudience: 'Audio enthusiasts, professionals, commuters, gamers',
      keyBenefits: 'Extended battery life, superior sound quality, comfortable fit for long sessions',
      competitiveAdvantage: 'Industry-leading 24-hour battery life with premium audio quality',
      seoKeywords: 'wireless headphones, bluetooth 5.0, 24 hour battery, foldable headphones, microphone',
      metaTitle: 'CD1234 Wireless Headphones - 24Hr Battery | Bluetooth 5.0 | Foldable',
      metaDescription: 'Experience premium audio with CD1234 wireless headphones featuring 24-hour battery, Bluetooth 5.0, and foldable design. Perfect for work and play.',
      productBullets: '• 24-hour extended battery life\n• Bluetooth 5.0 for stable connection\n• Foldable design for portability\n• Built-in microphone for hands-free calls\n• Active noise cancellation technology',
      technicalSpecs: 'Bluetooth Version: 5.0\nBattery Life: 24 hours\nCharging Time: 2 hours\nFrequency Response: 20Hz-20kHz\nWeight: 280g\nFoldable: Yes',
      useCases: 'Music listening, Video calls, Gaming, Commuting, Office work',
      warranty: '2 year warranty',
      certifications: 'CE, FCC, RoHS, Bluetooth SIG'
    },

    // Product 2: SPK789 - SmartHome Smart Speaker
    {
      id: 2,
      sku: 'SPK789',
      name: 'Smart Speaker with Voice Assistant',
      category: 'Electronics > Audio > Smart Speakers',
      brand: 'SmartHome',
      status: 'Enhanced',
      quality: 94,
      price: '$129.99',
      description: 'Premium smart speaker with 360° sound, multi-room audio, universal voice assistant support (Alexa/Google/Siri) and smart home hub integration',
      features: 'Voice assistant support, Multi-room audio, Smart home hub, 360° premium sound, Touch controls',
      targetAudience: 'Smart home enthusiasts, music lovers, homeowners, tech-savvy households',
      keyBenefits: 'Best-in-class sound quality, universal voice assistant compatibility, integrated smart home hub',
      competitiveAdvantage: 'Only speaker with all voice assistants + hub functionality at this price',
      seoKeywords: 'smart speaker, alexa compatible, google home, voice assistant, multi room audio',
      metaTitle: 'SPK789 Smart Speaker - Voice Control | Multi-Room Audio | Smart Hub',
      metaDescription: 'Transform your home with SPK789 smart speaker. Works with Alexa, Google, & Siri. Premium sound, multi-room audio, built-in smart home hub.',
      productBullets: '• Universal voice assistant support (Alexa/Google/Siri)\n• 360° premium audio quality\n• Multi-room audio synchronization\n• Built-in smart home hub (Zigbee + Z-Wave)\n• Touch controls & aux input',
      technicalSpecs: 'Power: 30W RMS\nFrequency: 50Hz-20kHz\nConnectivity: WiFi 802.11ac, Bluetooth 5.0, 3.5mm aux\nVoice: 4-mic far-field array\nDimensions: 6.5"H x 4"W',
      useCases: 'Music streaming, Smart home control, Voice queries, Podcast listening, Multi-room audio',
      warranty: '1 year warranty',
      certifications: 'CE, FCC, RoHS, WiFi Certified'
    },

    // Product 3: MON999 - ViewTech 4K Monitor
    {
      id: 3,
      sku: 'MON999',
      name: '4K Ultra HD Monitor',
      category: 'Electronics > Displays > Monitors',
      brand: 'ViewTech',
      status: 'Enhanced',
      quality: 93,
      price: '$449.99',
      description: 'Professional 32" 4K IPS monitor with 99% sRGB color accuracy, HDR10 support, USB-C power delivery, perfect for content creators and professionals',
      features: '32" 4K IPS display, 99% sRGB color accuracy, HDR10, USB-C with 65W PD, Height adjustable',
      targetAudience: 'Content creators, photographers, video editors, designers, remote workers',
      keyBenefits: 'True-to-life color accuracy, massive 4K workspace, USB-C single-cable solution',
      competitiveAdvantage: 'Professional color accuracy at consumer price with USB-C power delivery',
      seoKeywords: '4K monitor, color accurate monitor, USB-C monitor, monitor for photo editing, 32 inch monitor',
      metaTitle: 'MON999 4K Monitor - 32" | 99% sRGB | USB-C 65W | For Creators',
      metaDescription: 'Professional 32" 4K monitor with exceptional color accuracy. USB-C power delivery, HDR10, perfect for photo/video editing. ViewTech MON999.',
      productBullets: '• 32" 4K IPS panel (3840x2160)\n• 99% sRGB color accuracy out of box\n• HDR10 support for dynamic range\n• USB-C with 65W power delivery\n• VESA mount compatible, height adjustable',
      technicalSpecs: 'Panel: 32" IPS 4K (3840x2160), 60Hz\nColor: 99% sRGB, 90% DCI-P3, HDR10\nInputs: HDMI 2.0 x2, DisplayPort 1.4, USB-C (65W PD)\nStand: Tilt, height adjust, VESA 100x100',
      useCases: 'Photo editing, Video editing, Graphic design, Programming, General productivity',
      warranty: '3 year warranty',
      certifications: 'CE, FCC, RoHS, ENERGY STAR, TÜV Low Blue Light'
    }
  ];

  // Generate additional 197 SKUs for table views (IDs 4-200)
  const additionalProducts = [
    // TVs & Displays (30)
    { id: 4, sku: 'TV5543', name: 'Samsung 55" 4K QLED Smart TV', category: 'Electronics > Displays > Televisions', brand: 'Samsung', price: '$899.99', quality: 92 },
    { id: 5, sku: 'TV6543', name: 'LG 65" 4K OLED Smart TV', category: 'Electronics > Displays > Televisions', brand: 'LG', price: '$1,499.99', quality: 96 },
    { id: 6, sku: 'TV4332', name: 'TCL 43" 4K Roku TV', category: 'Electronics > Displays > Televisions', brand: 'TCL', price: '$349.99', quality: 85 },
    { id: 7, sku: 'TV7585', name: 'Sony 75" 4K LED Smart TV', category: 'Electronics > Displays > Televisions', brand: 'Sony', price: '$1,899.99', quality: 94 },
    { id: 8, sku: 'TV3243', name: 'Hisense 32" HD Smart TV', category: 'Electronics > Displays > Televisions', brand: 'Hisense', price: '$199.99', quality: 78 },
    { id: 9, sku: 'MON2724', name: 'Dell 27" 4K IPS Monitor', category: 'Electronics > Displays > Monitors', brand: 'Dell', price: '$449.99', quality: 91 },
    { id: 10, sku: 'MON3227', name: 'ASUS 32" 4K Gaming Monitor 144Hz', category: 'Electronics > Displays > Monitors', brand: 'ASUS', price: '$699.99', quality: 93 },
    { id: 11, sku: 'MON2427', name: 'ViewSonic 24" Full HD Monitor', category: 'Electronics > Displays > Monitors', brand: 'ViewSonic', price: '$149.99', quality: 82 },
    { id: 12, sku: 'MON3434', name: 'LG 34" UltraWide Curved Monitor', category: 'Electronics > Displays > Monitors', brand: 'LG', price: '$599.99', quality: 90 },
    { id: 13, sku: 'TV8585', name: 'Samsung 85" 8K QLED TV', category: 'Electronics > Displays > Televisions', brand: 'Samsung', price: '$2,499.99', quality: 97 },
    { id: 14, sku: 'TV5043', name: 'Sony 50" 4K Bravia TV', category: 'Electronics > Displays > Televisions', brand: 'Sony', price: '$749.99', quality: 89 },
    { id: 15, sku: 'MON2724G', name: 'MSI 27" Gaming Monitor 240Hz', category: 'Electronics > Displays > Monitors', brand: 'MSI', price: '$549.99', quality: 92 },
    { id: 16, sku: 'TV4350', name: 'Vizio 43" 4K Smart TV', category: 'Electronics > Displays > Televisions', brand: 'Vizio', price: '$329.99', quality: 84 },
    { id: 17, sku: 'MON1524', name: 'Portable 15.6" USB-C Monitor', category: 'Electronics > Displays > Monitors', brand: 'ASUS', price: '$249.99', quality: 86 },
    { id: 18, sku: 'PRJ4500', name: '4K Home Theater Projector', category: 'Electronics > Displays > Projectors', brand: 'Epson', price: '$1,299.99', quality: 91 },
    { id: 19, sku: 'TV6565', name: 'LG 65" NanoCell 4K TV', category: 'Electronics > Displays > Televisions', brand: 'LG', price: '$1,199.99', quality: 90 },
    { id: 20, sku: 'MON2827C', name: 'Samsung 28" 4K Curved Monitor', category: 'Electronics > Displays > Monitors', brand: 'Samsung', price: '$399.99', quality: 88 },
    { id: 21, sku: 'TV5555', name: 'Hisense 55" ULED 4K TV', category: 'Electronics > Displays > Televisions', brand: 'Hisense', price: '$649.99', quality: 87 },
    { id: 22, sku: 'MON3227U', name: 'BenQ 32" 4K Designer Monitor', category: 'Electronics > Displays > Monitors', brand: 'BenQ', price: '$799.99', quality: 93 },
    { id: 23, sku: 'TV7575', name: 'Sony 75" X90K 4K TV', category: 'Electronics > Displays > Televisions', brand: 'Sony', price: '$1,799.99', quality: 95 },
    { id: 24, sku: 'MON2424', name: 'HP 24" Full HD Monitor', category: 'Electronics > Displays > Monitors', brand: 'HP', price: '$129.99', quality: 80 },
    { id: 25, sku: 'TV8577', name: 'Samsung 85" Neo QLED 8K', category: 'Electronics > Displays > Televisions', brand: 'Samsung', price: '$3,499.99', quality: 98 },
    { id: 26, sku: 'MON4932', name: 'Samsung 49" Super Ultra Wide', category: 'Electronics > Displays > Monitors', brand: 'Samsung', price: '$1,099.99', quality: 94 },
    { id: 27, sku: 'PRJ3000', name: 'Portable Mini Projector', category: 'Electronics > Displays > Projectors', brand: 'Anker', price: '$299.99', quality: 83 },
    { id: 28, sku: 'TV6060', name: 'TCL 60" 4K QLED TV', category: 'Electronics > Displays > Televisions', brand: 'TCL', price: '$699.99', quality: 86 },
    { id: 29, sku: 'MON2727P', name: 'Dell 27" QHD Professional Monitor', category: 'Electronics > Displays > Monitors', brand: 'Dell', price: '$549.99', quality: 90 },
    { id: 30, sku: 'TV4848', name: 'LG 48" OLED C3 TV', category: 'Electronics > Displays > Televisions', brand: 'LG', price: '$1,299.99', quality: 96 },
    { id: 31, sku: 'MON3429', name: 'LG 34" UltraWide 5K Monitor', category: 'Electronics > Displays > Monitors', brand: 'LG', price: '$899.99', quality: 92 },
    { id: 32, sku: 'TV5565', name: 'Vizio 55" OLED 4K TV', category: 'Electronics > Displays > Televisions', brand: 'Vizio', price: '$999.99', quality: 89 },
    { id: 33, sku: 'PRJ5000', name: 'Laser 4K Projector', category: 'Electronics > Displays > Projectors', brand: 'LG', price: '$2,199.99', quality: 93 },

    // Audio (35)
    { id: 34, sku: 'AUD456', name: 'Sony WF-1000XM5 True Wireless Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Sony', price: '$299.99', quality: 95 },
    { id: 35, sku: 'AUD789', name: 'Bose QuietComfort 45 Headphones', category: 'Electronics > Audio > Headphones', brand: 'Bose', price: '$329.99', quality: 94 },
    { id: 36, sku: 'AUD234', name: 'Sonos One Smart Speaker', category: 'Electronics > Audio > Smart Speakers', brand: 'Sonos', price: '$219.99', quality: 93 },
    { id: 37, sku: 'AUD567', name: 'JBL Flip 6 Portable Bluetooth Speaker', category: 'Electronics > Audio > Speakers', brand: 'JBL', price: '$129.99', quality: 88 },
    { id: 38, sku: 'AUD890', name: 'Sennheiser HD 660S Headphones', category: 'Electronics > Audio > Headphones', brand: 'Sennheiser', price: '$499.99', quality: 96 },
    { id: 39, sku: 'AUD123', name: 'Beats Studio Buds+ Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Beats', price: '$169.99', quality: 87 },
    { id: 40, sku: 'AUD345', name: 'Anker Soundcore Life Q30 Headphones', category: 'Electronics > Audio > Headphones', brand: 'Anker', price: '$79.99', quality: 85 },
    { id: 41, sku: 'AUD678', name: 'Jabra Elite 85t Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Jabra', price: '$229.99', quality: 91 },
    { id: 42, sku: 'AUD901', name: 'Audio-Technica ATH-M50x Headphones', category: 'Electronics > Audio > Headphones', brand: 'Audio-Technica', price: '$149.99', quality: 92 },
    { id: 43, sku: 'AUD445', name: 'Bose SoundLink Revolve+ Speaker', category: 'Electronics > Audio > Speakers', brand: 'Bose', price: '$299.99', quality: 90 },
    { id: 44, sku: 'AUD556', name: 'Sony WH-1000XM5 Headphones', category: 'Electronics > Audio > Headphones', brand: 'Sony', price: '$399.99', quality: 97 },
    { id: 45, sku: 'AUD667', name: 'JBL Charge 5 Portable Speaker', category: 'Electronics > Audio > Speakers', brand: 'JBL', price: '$179.99', quality: 89 },
    { id: 46, sku: 'AUD778', name: 'Apple AirPods Pro 2nd Gen', category: 'Electronics > Audio > Earbuds', brand: 'Apple', price: '$249.99', quality: 95 },
    { id: 47, sku: 'AUD889', name: 'Sonos Arc Soundbar', category: 'Electronics > Audio > Soundbars', brand: 'Sonos', price: '$899.99', quality: 96 },
    { id: 48, sku: 'AUD990', name: 'Blue Yeti USB Microphone', category: 'Electronics > Audio > Microphones', brand: 'Blue', price: '$129.99', quality: 90 },
    { id: 49, sku: 'AUD111', name: 'Bose SoundLink Mini II Speaker', category: 'Electronics > Audio > Speakers', brand: 'Bose', price: '$199.99', quality: 88 },
    { id: 50, sku: 'AUD222', name: 'Samsung Galaxy Buds2 Pro', category: 'Electronics > Audio > Earbuds', brand: 'Samsung', price: '$229.99', quality: 90 },
    { id: 51, sku: 'AUD333', name: 'Beats Solo3 Wireless Headphones', category: 'Electronics > Audio > Headphones', brand: 'Beats', price: '$199.99', quality: 86 },
    { id: 52, sku: 'AUD444', name: 'JBL PartyBox 310 Speaker', category: 'Electronics > Audio > Speakers', brand: 'JBL', price: '$549.99', quality: 87 },
    { id: 53, sku: 'AUD555', name: 'Shure MV7 Podcast Microphone', category: 'Electronics > Audio > Microphones', brand: 'Shure', price: '$249.99', quality: 93 },
    { id: 54, sku: 'AUD666', name: 'Sonos Beam Soundbar Gen 2', category: 'Electronics > Audio > Soundbars', brand: 'Sonos', price: '$499.99', quality: 92 },
    { id: 55, sku: 'AUD777', name: 'Anker Soundcore Liberty 4 Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Anker', price: '$149.99', quality: 86 },
    { id: 56, sku: 'AUD888', name: 'Bose 700 Noise Cancelling Headphones', category: 'Electronics > Audio > Headphones', brand: 'Bose', price: '$379.99', quality: 94 },
    { id: 57, sku: 'AUD999', name: 'Ultimate Ears BOOM 3 Speaker', category: 'Electronics > Audio > Speakers', brand: 'Ultimate Ears', price: '$149.99', quality: 87 },
    { id: 58, sku: 'AUD100', name: 'Rode NT-USB Mini Microphone', category: 'Electronics > Audio > Microphones', brand: 'Rode', price: '$99.99', quality: 88 },
    { id: 59, sku: 'AUD200', name: 'Klipsch The Three II Speaker', category: 'Electronics > Audio > Speakers', brand: 'Klipsch', price: '$499.99', quality: 91 },
    { id: 60, sku: 'AUD300', name: 'Sennheiser Momentum 4 Wireless', category: 'Electronics > Audio > Headphones', brand: 'Sennheiser', price: '$379.99', quality: 95 },
    { id: 61, sku: 'AUD400', name: 'Nothing Ear (2) Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Nothing', price: '$149.99', quality: 85 },
    { id: 62, sku: 'AUD500', name: 'Bose Smart Soundbar 900', category: 'Electronics > Audio > Soundbars', brand: 'Bose', price: '$899.99', quality: 95 },
    { id: 63, sku: 'AUD600', name: 'Marshall Emberton II Speaker', category: 'Electronics > Audio > Speakers', brand: 'Marshall', price: '$169.99', quality: 88 },
    { id: 64, sku: 'AUD700', name: 'Sony WF-C700N Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Sony', price: '$119.99', quality: 84 },
    { id: 65, sku: 'AUD800', name: 'HyperX Cloud II Gaming Headset', category: 'Electronics > Audio > Headphones', brand: 'HyperX', price: '$99.99', quality: 87 },
    { id: 66, sku: 'AUD900', name: 'Edifier R1280T Bookshelf Speakers', category: 'Electronics > Audio > Speakers', brand: 'Edifier', price: '$99.99', quality: 83 },
    { id: 67, sku: 'AUD950', name: 'Elgato Wave:3 Microphone', category: 'Electronics > Audio > Microphones', brand: 'Elgato', price: '$159.99', quality: 89 },
    { id: 68, sku: 'AUD975', name: 'JBL Bar 5.1 Surround Soundbar', category: 'Electronics > Audio > Soundbars', brand: 'JBL', price: '$599.99', quality: 90 },

    // Computing (30)
    { id: 69, sku: 'LAP892', name: 'Dell XPS 13 Ultrabook', category: 'Electronics > Computing > Laptops', brand: 'Dell', price: '$1,299.99', quality: 94 },
    { id: 70, sku: 'LAP456', name: 'HP Pavilion 15 Laptop', category: 'Electronics > Computing > Laptops', brand: 'HP', price: '$749.99', quality: 86 },
    { id: 71, sku: 'LAP789', name: 'MacBook Air M2', category: 'Electronics > Computing > Laptops', brand: 'Apple', price: '$1,199.99', quality: 97 },
    { id: 72, sku: 'LAP123', name: 'ASUS ROG Zephyrus Gaming Laptop', category: 'Electronics > Computing > Laptops', brand: 'ASUS', price: '$1,899.99', quality: 95 },
    { id: 73, sku: 'LAP345', name: 'Lenovo ThinkPad X1 Carbon', category: 'Electronics > Computing > Laptops', brand: 'Lenovo', price: '$1,599.99', quality: 93 },
    { id: 74, sku: 'TAB567', name: 'iPad Pro 12.9"', category: 'Electronics > Computing > Tablets', brand: 'Apple', price: '$1,099.99', quality: 96 },
    { id: 75, sku: 'TAB890', name: 'Samsung Galaxy Tab S9', category: 'Electronics > Computing > Tablets', brand: 'Samsung', price: '$799.99', quality: 92 },
    { id: 76, sku: 'TAB234', name: 'Amazon Fire HD 10', category: 'Electronics > Computing > Tablets', brand: 'Amazon', price: '$149.99', quality: 79 },
    { id: 77, sku: 'KEY456', name: 'Logitech MX Keys Mechanical Keyboard', category: 'Electronics > Computing > Keyboards', brand: 'Logitech', price: '$169.99', quality: 92 },
    { id: 78, sku: 'KEY789', name: 'Corsair K95 RGB Gaming Keyboard', category: 'Electronics > Computing > Keyboards', brand: 'Corsair', price: '$199.99', quality: 90 },
    { id: 79, sku: 'KEY123', name: 'Keychron K2 Wireless Mechanical', category: 'Electronics > Computing > Keyboards', brand: 'Keychron', price: '$89.99', quality: 88 },
    { id: 80, sku: 'MOU456', name: 'Logitech MX Master 3S Mouse', category: 'Electronics > Computing > Mice', brand: 'Logitech', price: '$99.99', quality: 94 },
    { id: 81, sku: 'MOU789', name: 'Razer DeathAdder V3 Gaming Mouse', category: 'Electronics > Computing > Mice', brand: 'Razer', price: '$69.99', quality: 91 },
    { id: 82, sku: 'MOU123', name: 'Apple Magic Mouse', category: 'Electronics > Computing > Mice', brand: 'Apple', price: '$79.99', quality: 85 },
    { id: 83, sku: 'CAM789', name: 'Logitech C920 HD Webcam', category: 'Electronics > Computing > Webcams', brand: 'Logitech', price: '$79.99', quality: 88 },
    { id: 84, sku: 'CAM345', name: 'Razer Kiyo Pro Ultra 4K Webcam', category: 'Electronics > Computing > Webcams', brand: 'Razer', price: '$299.99', quality: 93 },
    { id: 85, sku: 'LAP678', name: 'Microsoft Surface Laptop 5', category: 'Electronics > Computing > Laptops', brand: 'Microsoft', price: '$999.99', quality: 91 },
    { id: 86, sku: 'LAP901', name: 'Acer Swift 3 Laptop', category: 'Electronics > Computing > Laptops', brand: 'Acer', price: '$699.99', quality: 84 },
    { id: 87, sku: 'TAB678', name: 'Microsoft Surface Pro 9', category: 'Electronics > Computing > Tablets', brand: 'Microsoft', price: '$999.99', quality: 93 },
    { id: 88, sku: 'TAB901', name: 'Lenovo Tab P11 Pro', category: 'Electronics > Computing > Tablets', brand: 'Lenovo', price: '$499.99', quality: 87 },
    { id: 89, sku: 'KEY345', name: 'Razer BlackWidow V4 Keyboard', category: 'Electronics > Computing > Keyboards', brand: 'Razer', price: '$179.99', quality: 89 },
    { id: 90, sku: 'KEY678', name: 'Microsoft Ergonomic Keyboard', category: 'Electronics > Computing > Keyboards', brand: 'Microsoft', price: '$59.99', quality: 83 },
    { id: 91, sku: 'MOU345', name: 'Logitech G502 HERO Gaming Mouse', category: 'Electronics > Computing > Mice', brand: 'Logitech', price: '$79.99', quality: 90 },
    { id: 92, sku: 'MOU678', name: 'Microsoft Ergonomic Mouse', category: 'Electronics > Computing > Mice', brand: 'Microsoft', price: '$49.99', quality: 82 },
    { id: 93, sku: 'CAM567', name: 'Elgato Facecam Pro 4K Webcam', category: 'Electronics > Computing > Webcams', brand: 'Elgato', price: '$249.99', quality: 92 },
    { id: 94, sku: 'ACC123', name: 'Laptop Stand Aluminum', category: 'Electronics > Computing > Accessories', brand: 'Rain Design', price: '$49.99', quality: 86 },
    { id: 95, sku: 'ACC456', name: 'USB-C Hub 7-in-1', category: 'Electronics > Computing > Accessories', brand: 'Anker', price: '$59.99', quality: 87 },
    { id: 96, sku: 'LAP234', name: 'ASUS VivoBook 15', category: 'Electronics > Computing > Laptops', brand: 'ASUS', price: '$599.99', quality: 82 },
    { id: 97, sku: 'TAB345', name: 'iPad Air 5th Gen', category: 'Electronics > Computing > Tablets', brand: 'Apple', price: '$599.99', quality: 94 },
    { id: 98, sku: 'MOU901', name: 'Logitech MX Vertical Ergonomic Mouse', category: 'Electronics > Computing > Mice', brand: 'Logitech', price: '$99.99', quality: 89 },

    // Mobile Accessories (25)
    { id: 99, sku: 'PHN123', name: 'iPhone 15 Pro', category: 'Electronics > Mobile > Smartphones', brand: 'Apple', price: '$999.99', quality: 97 },
    { id: 100, sku: 'PHN456', name: 'Samsung Galaxy S24 Ultra', category: 'Electronics > Mobile > Smartphones', brand: 'Samsung', price: '$1,199.99', quality: 96 },
    { id: 101, sku: 'PHN789', name: 'Google Pixel 8 Pro', category: 'Electronics > Mobile > Smartphones', brand: 'Google', price: '$899.99', quality: 94 },
    { id: 102, sku: 'CAS123', name: 'OtterBox Defender iPhone Case', category: 'Electronics > Mobile > Cases', brand: 'OtterBox', price: '$49.99', quality: 90 },
    { id: 103, sku: 'CAS456', name: 'Spigen Ultra Hybrid Case', category: 'Electronics > Mobile > Cases', brand: 'Spigen', price: '$19.99', quality: 85 },
    { id: 104, sku: 'CAS789', name: 'Apple Silicone iPhone Case', category: 'Electronics > Mobile > Cases', brand: 'Apple', price: '$49.99', quality: 88 },
    { id: 105, sku: 'SCR123', name: 'Tempered Glass Screen Protector 2-Pack', category: 'Electronics > Mobile > Protection', brand: 'AmFilm', price: '$9.99', quality: 83 },
    { id: 106, sku: 'PWR123', name: 'Anker PowerCore 20000mAh Power Bank', category: 'Electronics > Mobile > Chargers', brand: 'Anker', price: '$49.99', quality: 91 },
    { id: 107, sku: 'PWR456', name: 'Anker 30000mAh USB-C Power Bank', category: 'Electronics > Mobile > Chargers', brand: 'Anker', price: '$79.99', quality: 92 },
    { id: 108, sku: 'PWR789', name: 'Belkin 10000mAh Wireless Power Bank', category: 'Electronics > Mobile > Chargers', brand: 'Belkin', price: '$59.99', quality: 88 },
    { id: 109, sku: 'CBL123', name: 'USB-C to Lightning Cable 6ft', category: 'Electronics > Mobile > Cables', brand: 'Anker', price: '$19.99', quality: 86 },
    { id: 110, sku: 'CBL456', name: 'Braided USB-C Cable 3-Pack', category: 'Electronics > Mobile > Cables', brand: 'UGREEN', price: '$24.99', quality: 84 },
    { id: 111, sku: 'CHG123', name: 'Anker 65W USB-C Wall Charger', category: 'Electronics > Mobile > Chargers', brand: 'Anker', price: '$39.99', quality: 90 },
    { id: 112, sku: 'CHG456', name: 'Belkin 3-in-1 Wireless Charger', category: 'Electronics > Mobile > Chargers', brand: 'Belkin', price: '$129.99', quality: 91 },
    { id: 113, sku: 'MNT123', name: 'Magnetic Car Phone Mount', category: 'Electronics > Mobile > Mounts', brand: 'iOttie', price: '$29.99', quality: 87 },
    { id: 114, sku: 'MNT456', name: 'Dashboard Phone Holder', category: 'Electronics > Mobile > Mounts', brand: 'Mpow', price: '$19.99', quality: 82 },
    { id: 115, sku: 'PHN234', name: 'OnePlus 12 Smartphone', category: 'Electronics > Mobile > Smartphones', brand: 'OnePlus', price: '$799.99', quality: 92 },
    { id: 116, sku: 'PHN567', name: 'Xiaomi 13 Pro', category: 'Electronics > Mobile > Smartphones', brand: 'Xiaomi', price: '$899.99', quality: 91 },
    { id: 117, sku: 'CAS234', name: 'Leather Wallet iPhone Case', category: 'Electronics > Mobile > Cases', brand: 'Bellroy', price: '$69.99', quality: 89 },
    { id: 118, sku: 'PWR234', name: 'RAVPower 26800mAh Power Bank', category: 'Electronics > Mobile > Chargers', brand: 'RAVPower', price: '$69.99', quality: 90 },
    { id: 119, sku: 'CHG789', name: 'Apple MagSafe Charger', category: 'Electronics > Mobile > Chargers', brand: 'Apple', price: '$39.99', quality: 93 },
    { id: 120, sku: 'MNT789', name: 'Adjustable Phone Stand', category: 'Electronics > Mobile > Stands', brand: 'Lamicall', price: '$14.99', quality: 81 },
    { id: 121, sku: 'CBL789', name: 'Apple USB-C to Lightning Cable', category: 'Electronics > Mobile > Cables', brand: 'Apple', price: '$29.99', quality: 92 },
    { id: 122, sku: 'CAS567', name: 'Samsung Silicone Case', category: 'Electronics > Mobile > Cases', brand: 'Samsung', price: '$29.99', quality: 86 },
    { id: 123, sku: 'SCR456', name: 'Privacy Screen Protector', category: 'Electronics > Mobile > Protection', brand: 'ZAGG', price: '$39.99', quality: 88 },

    // Smart Home (25)
    { id: 124, sku: 'SMT123', name: 'Ring Video Doorbell Pro 2', category: 'Electronics > Smart Home > Doorbells', brand: 'Ring', price: '$249.99', quality: 92 },
    { id: 125, sku: 'SMT456', name: 'Nest Learning Thermostat', category: 'Electronics > Smart Home > Thermostats', brand: 'Nest', price: '$249.99', quality: 94 },
    { id: 126, sku: 'SMT789', name: 'Arlo Pro 4 Security Camera 2-Pack', category: 'Electronics > Smart Home > Cameras', brand: 'Arlo', price: '$299.99', quality: 91 },
    { id: 127, sku: 'SMT234', name: 'Philips Hue White & Color 4-Bulb Starter Kit', category: 'Electronics > Smart Home > Lighting', brand: 'Philips Hue', price: '$199.99', quality: 93 },
    { id: 128, sku: 'SMT567', name: 'TP-Link Kasa Smart Plug 4-Pack', category: 'Electronics > Smart Home > Plugs', brand: 'TP-Link', price: '$39.99', quality: 86 },
    { id: 129, sku: 'SMT890', name: 'August Smart Lock Pro', category: 'Electronics > Smart Home > Locks', brand: 'August', price: '$229.99', quality: 90 },
    { id: 130, sku: 'SMT345', name: 'Wyze Cam v3 Indoor/Outdoor Camera', category: 'Electronics > Smart Home > Cameras', brand: 'Wyze', price: '$35.99', quality: 84 },
    { id: 131, sku: 'SMT678', name: 'ecobee SmartThermostat Premium', category: 'Electronics > Smart Home > Thermostats', brand: 'ecobee', price: '$259.99', quality: 93 },
    { id: 132, sku: 'SMT901', name: 'Ring Indoor Cam', category: 'Electronics > Smart Home > Cameras', brand: 'Ring', price: '$59.99', quality: 85 },
    { id: 133, sku: 'SMT111', name: 'Philips Hue LED Light Strip 6ft', category: 'Electronics > Smart Home > Lighting', brand: 'Philips Hue', price: '$79.99', quality: 89 },
    { id: 134, sku: 'SMT222', name: 'Samsung SmartThings Hub', category: 'Electronics > Smart Home > Hubs', brand: 'Samsung', price: '$89.99', quality: 87 },
    { id: 135, sku: 'SMT333', name: 'Lutron Caseta Smart Dimmer Switch', category: 'Electronics > Smart Home > Switches', brand: 'Lutron', price: '$59.99', quality: 90 },
    { id: 136, sku: 'SMT444', name: 'Ring Alarm 8-piece Security Kit', category: 'Electronics > Smart Home > Security', brand: 'Ring', price: '$199.99', quality: 91 },
    { id: 137, sku: 'SMT555', name: 'Arlo Essential Video Doorbell', category: 'Electronics > Smart Home > Doorbells', brand: 'Arlo', price: '$149.99', quality: 88 },
    { id: 138, sku: 'SMT666', name: 'Eve Motion Sensor', category: 'Electronics > Smart Home > Sensors', brand: 'Eve', price: '$39.99', quality: 83 },
    { id: 139, sku: 'SMT777', name: 'Yale Assure Lock 2', category: 'Electronics > Smart Home > Locks', brand: 'Yale', price: '$279.99', quality: 92 },
    { id: 140, sku: 'SMT888', name: 'Google Nest Cam Indoor', category: 'Electronics > Smart Home > Cameras', brand: 'Nest', price: '$99.99', quality: 89 },
    { id: 141, sku: 'SMT999', name: 'Philips Hue Play Light Bar 2-Pack', category: 'Electronics > Smart Home > Lighting', brand: 'Philips Hue', price: '$139.99', quality: 90 },
    { id: 142, sku: 'SMT100', name: 'TP-Link Tapo Smart Bulb 4-Pack', category: 'Electronics > Smart Home > Lighting', brand: 'TP-Link', price: '$34.99', quality: 82 },
    { id: 143, sku: 'SMT200', name: 'Ring Floodlight Cam Wired Plus', category: 'Electronics > Smart Home > Cameras', brand: 'Ring', price: '$199.99', quality: 90 },
    { id: 144, sku: 'SMT300', name: 'Honeywell Home T9 Thermostat', category: 'Electronics > Smart Home > Thermostats', brand: 'Honeywell', price: '$199.99', quality: 88 },
    { id: 145, sku: 'SMT400', name: 'Kasa Smart Light Switch 3-Way', category: 'Electronics > Smart Home > Switches', brand: 'TP-Link', price: '$49.99', quality: 85 },
    { id: 146, sku: 'SMT500', name: 'Nest Protect Smoke Detector', category: 'Electronics > Smart Home > Sensors', brand: 'Nest', price: '$119.99', quality: 91 },
    { id: 147, sku: 'SMT600', name: 'Schlage Encode Smart Lock', category: 'Electronics > Smart Home > Locks', brand: 'Schlage', price: '$299.99', quality: 93 },
    { id: 148, sku: 'SMT700', name: 'Blink Outdoor 3-Camera System', category: 'Electronics > Smart Home > Cameras', brand: 'Blink', price: '$199.99', quality: 86 },

    // Gaming (20)
    { id: 149, sku: 'GAM567', name: 'Xbox Series X Console', category: 'Electronics > Gaming > Consoles', brand: 'Microsoft', price: '$499.99', quality: 96 },
    { id: 150, sku: 'GAM890', name: 'PlayStation 5 Console', category: 'Electronics > Gaming > Consoles', brand: 'Sony', price: '$499.99', quality: 97 },
    { id: 151, sku: 'GAM123', name: 'Nintendo Switch OLED', category: 'Electronics > Gaming > Consoles', brand: 'Nintendo', price: '$349.99', quality: 94 },
    { id: 152, sku: 'GAM456', name: 'Xbox Elite Controller Series 2', category: 'Electronics > Gaming > Controllers', brand: 'Microsoft', price: '$179.99', quality: 93 },
    { id: 153, sku: 'GAM789', name: 'DualSense Wireless Controller', category: 'Electronics > Gaming > Controllers', brand: 'Sony', price: '$69.99', quality: 91 },
    { id: 154, sku: 'GAM234', name: 'Razer Kraken Gaming Headset', category: 'Electronics > Gaming > Headsets', brand: 'Razer', price: '$79.99', quality: 88 },
    { id: 155, sku: 'GAM345', name: 'SteelSeries Arctis Nova Pro Wireless', category: 'Electronics > Gaming > Headsets', brand: 'SteelSeries', price: '$349.99', quality: 95 },
    { id: 156, sku: 'GAM678', name: 'Logitech G923 Racing Wheel', category: 'Electronics > Gaming > Accessories', brand: 'Logitech', price: '$399.99', quality: 92 },
    { id: 157, sku: 'GAM901', name: 'Razer Wolverine V2 Pro Controller', category: 'Electronics > Gaming > Controllers', brand: 'Razer', price: '$249.99', quality: 90 },
    { id: 158, sku: 'GAM111', name: 'Meta Quest 3 VR Headset', category: 'Electronics > Gaming > VR', brand: 'Meta', price: '$499.99', quality: 94 },
    { id: 159, sku: 'GAM222', name: 'HyperX Cloud Alpha Wireless Headset', category: 'Electronics > Gaming > Headsets', brand: 'HyperX', price: '$199.99', quality: 91 },
    { id: 160, sku: 'GAM333', name: 'Secretlab Titan Evo Gaming Chair', category: 'Electronics > Gaming > Furniture', brand: 'Secretlab', price: '$549.99', quality: 95 },
    { id: 161, sku: 'GAM444', name: '8BitDo Pro 2 Controller', category: 'Electronics > Gaming > Controllers', brand: '8BitDo', price: '$49.99', quality: 87 },
    { id: 162, sku: 'GAM555', name: 'Thrustmaster T.Flight HOTAS One', category: 'Electronics > Gaming > Accessories', brand: 'Thrustmaster', price: '$79.99', quality: 86 },
    { id: 163, sku: 'GAM666', name: 'PlayStation VR2', category: 'Electronics > Gaming > VR', brand: 'Sony', price: '$549.99', quality: 93 },
    { id: 164, sku: 'GAM777', name: 'Corsair K70 RGB Gaming Keyboard', category: 'Electronics > Gaming > Keyboards', brand: 'Corsair', price: '$179.99', quality: 90 },
    { id: 165, sku: 'GAM888', name: 'Razer Basilisk V3 Gaming Mouse', category: 'Electronics > Gaming > Mice', brand: 'Razer', price: '$69.99', quality: 89 },
    { id: 166, sku: 'GAM999', name: 'Elgato Stream Deck', category: 'Electronics > Gaming > Streaming', brand: 'Elgato', price: '$149.99', quality: 92 },
    { id: 167, sku: 'GAM100', name: 'Nintendo Switch Pro Controller', category: 'Electronics > Gaming > Controllers', brand: 'Nintendo', price: '$69.99', quality: 90 },
    { id: 168, sku: 'GAM200', name: 'Razer Enki Gaming Chair', category: 'Electronics > Gaming > Furniture', brand: 'Razer', price: '$399.99', quality: 89 },

    // Wearables (15)
    { id: 169, sku: 'WAT123', name: 'Apple Watch Series 9', category: 'Electronics > Wearables > Smartwatches', brand: 'Apple', price: '$399.99', quality: 97 },
    { id: 170, sku: 'WAT456', name: 'Samsung Galaxy Watch 6', category: 'Electronics > Wearables > Smartwatches', brand: 'Samsung', price: '$299.99', quality: 93 },
    { id: 171, sku: 'WAT789', name: 'Fitbit Charge 6', category: 'Electronics > Wearables > Fitness Trackers', brand: 'Fitbit', price: '$159.99', quality: 89 },
    { id: 172, sku: 'WAT234', name: 'Garmin Forerunner 965', category: 'Electronics > Wearables > Smartwatches', brand: 'Garmin', price: '$599.99', quality: 95 },
    { id: 173, sku: 'WAT567', name: 'Amazfit GTR 4', category: 'Electronics > Wearables > Smartwatches', brand: 'Amazfit', price: '$199.99', quality: 87 },
    { id: 174, sku: 'WAT890', name: 'Fitbit Inspire 3', category: 'Electronics > Wearables > Fitness Trackers', brand: 'Fitbit', price: '$99.99', quality: 85 },
    { id: 175, sku: 'WAT111', name: 'Garmin Venu 3', category: 'Electronics > Wearables > Smartwatches', brand: 'Garmin', price: '$449.99', quality: 92 },
    { id: 176, sku: 'WAT222', name: 'Whoop 4.0', category: 'Electronics > Wearables > Fitness Trackers', brand: 'Whoop', price: '$239.99', quality: 90 },
    { id: 177, sku: 'WAT333', name: 'Oura Ring Gen 3', category: 'Electronics > Wearables > Smart Rings', brand: 'Oura', price: '$299.99', quality: 91 },
    { id: 178, sku: 'WAT444', name: 'Polar Vantage V3', category: 'Electronics > Wearables > Smartwatches', brand: 'Polar', price: '$599.99', quality: 93 },
    { id: 179, sku: 'WAT555', name: 'Xiaomi Mi Band 8', category: 'Electronics > Wearables > Fitness Trackers', brand: 'Xiaomi', price: '$49.99', quality: 82 },
    { id: 180, sku: 'WAT666', name: 'Apple Watch Ultra 2', category: 'Electronics > Wearables > Smartwatches', brand: 'Apple', price: '$799.99', quality: 98 },
    { id: 181, sku: 'WAT777', name: 'Garmin Fenix 7X', category: 'Electronics > Wearables > Smartwatches', brand: 'Garmin', price: '$899.99', quality: 96 },
    { id: 182, sku: 'WAT888', name: 'Withings ScanWatch', category: 'Electronics > Wearables > Smartwatches', brand: 'Withings', price: '$279.99', quality: 88 },
    { id: 183, sku: 'WAT999', name: 'Coros Pace 3', category: 'Electronics > Wearables > Smartwatches', brand: 'Coros', price: '$229.99', quality: 86 },

    // Photography (10)
    { id: 184, sku: 'CAM123', name: 'Sony A7 IV Mirrorless Camera', category: 'Electronics > Photography > Cameras', brand: 'Sony', price: '$2,499.99', quality: 96 },
    { id: 185, sku: 'CAM456', name: 'Canon EOS R6 Mark II', category: 'Electronics > Photography > Cameras', brand: 'Canon', price: '$2,099.99', quality: 95 },
    { id: 186, sku: 'CAM890', name: 'GoPro HERO12 Black', category: 'Electronics > Photography > Action Cameras', brand: 'GoPro', price: '$399.99', quality: 92 },
    { id: 187, sku: 'DRN445', name: 'DJI Mini 3 Pro Drone', category: 'Electronics > Photography > Drones', brand: 'DJI', price: '$759.99', quality: 93 },
    { id: 188, sku: 'DRN678', name: 'DJI Air 3 Drone', category: 'Electronics > Photography > Drones', brand: 'DJI', price: '$1,099.99', quality: 94 },
    { id: 189, sku: 'CAM234', name: 'Insta360 X3 Action Camera', category: 'Electronics > Photography > Action Cameras', brand: 'Insta360', price: '$449.99', quality: 90 },
    { id: 190, sku: 'ACC789', name: 'Manfrotto Carbon Fiber Tripod', category: 'Electronics > Photography > Accessories', brand: 'Manfrotto', price: '$299.99', quality: 91 },
    { id: 191, sku: 'ACC234', name: 'DJI RS 3 Pro Gimbal', category: 'Electronics > Photography > Gimbals', brand: 'DJI', price: '$869.99', quality: 93 },
    { id: 192, sku: 'DRN901', name: 'DJI Mavic 3 Classic', category: 'Electronics > Photography > Drones', brand: 'DJI', price: '$1,599.99', quality: 95 },
    { id: 193, sku: 'CAM567', name: 'Nikon Z8 Mirrorless Camera', category: 'Electronics > Photography > Cameras', brand: 'Nikon', price: '$3,999.99', quality: 97 },

    // Networking (5)
    { id: 194, sku: 'NET678', name: 'TP-Link AX6000 WiFi 6 Router', category: 'Electronics > Networking > Routers', brand: 'TP-Link', price: '$299.99', quality: 89 },
    { id: 195, sku: 'NET123', name: 'Netgear Orbi WiFi 6E Mesh System', category: 'Electronics > Networking > Mesh Systems', brand: 'Netgear', price: '$699.99', quality: 93 },
    { id: 196, sku: 'NET456', name: 'ASUS RT-AX88U Gaming Router', category: 'Electronics > Networking > Routers', brand: 'ASUS', price: '$349.99', quality: 91 },
    { id: 197, sku: 'NET789', name: 'TP-Link RE705X WiFi 6 Range Extender', category: 'Electronics > Networking > Extenders', brand: 'TP-Link', price: '$119.99', quality: 85 },
    { id: 198, sku: 'NET234', name: 'Google Nest WiFi Pro 6E', category: 'Electronics > Networking > Mesh Systems', brand: 'Google', price: '$399.99', quality: 90 },

    // Storage (7)
    { id: 199, sku: 'STO901', name: 'Samsung T7 2TB Portable SSD', category: 'Electronics > Storage > SSDs', brand: 'Samsung', price: '$199.99', quality: 93 },
    { id: 200, sku: 'STO123', name: 'WD My Passport 4TB External HDD', category: 'Electronics > Storage > HDDs', brand: 'Western Digital', price: '$99.99', quality: 87 }
  ];

  // Add realistic but minimal data for additional products
  const enrichedAdditional = additionalProducts.map(product => ({
    ...product,
    status: product.quality >= 90 ? 'Enhanced' as const : 'Needs Review' as const,
    description: `${product.name} offers premium quality and features for ${product.category.split(' > ').pop()?.toLowerCase()} enthusiasts`,
    features: 'Advanced features, Premium build quality, Latest technology, User-friendly design',
    targetAudience: 'Tech enthusiasts, professionals, everyday users',
    keyBenefits: 'Superior performance, reliability, and value',
    competitiveAdvantage: 'Industry-leading features at competitive price point',
    seoKeywords: product.name.toLowerCase().split(' ').slice(0, 5).join(', '),
    metaTitle: `${product.name} | ${product.brand} | ${product.price}`,
    metaDescription: `Buy ${product.name} from ${product.brand}. Premium quality ${product.category.split(' > ').pop()?.toLowerCase()} with advanced features. ${product.price}`,
    productBullets: `• ${product.brand} quality and reliability\n• Advanced features and performance\n• Premium design and build\n• Great value at ${product.price}`,
    technicalSpecs: 'Premium materials, Latest technology, Industry-standard certifications',
    useCases: 'Daily use, Professional applications, Entertainment, Productivity',
    warranty: product.quality >= 95 ? '3 year warranty' : product.quality >= 90 ? '2 year warranty' : '1 year warranty',
    certifications: 'CE, FCC, RoHS'
  }));

  return [...assets, ...enrichedAdditional];
};
