import { EnrichmentAsset } from '@/types/enrichmentAsset';

export const generateSampleEnrichmentAssets = (): EnrichmentAsset[] => {
  const baseAssets: EnrichmentAsset[] = [
    {
      id: 1,
      sku: "CD1234",
      name: "CD1234 24 Hour Charge Wireless Headphones",
      brand: "TechSound",
      category: "Electronics > Audio > Headphones",
      status: "Enriched",
      quality: 95,
      searchTrends: "High demand for 'wireless headphones long battery', 'bluetooth headphones 24 hour'",
      customerSentiment: "Positive (4.2/5) - Users love battery life, comfort concerns noted",
      socialMentions: "312 mentions/month - mostly positive, trending in gaming communities",
      competitorAnalysis: "Beats Studio3 (20hrs), Sony WH-1000XM4 (30hrs) - our 24hr is competitive",
      seoOpportunities: "Target 'best long battery headphones', 'wireless headphones for travel'",
      targetAudience: "Business travelers, remote workers, gamers aged 25-45",
      keyFeatures: "24-hour battery, Bluetooth 5.0, foldable design, quick charge",
      seoKeywordVolume: "'wireless headphones long battery' (8,200 searches/month)",
      reasonsToBuy: "1. Exceptional 24-hour battery life (95% confidence)\n2. Superior sound quality for price point (87% confidence)",
      categoryEntryPoints: "Travel & Lifestyle Changes: Flying next week, need better travel headphones",
      favouriteFeatures: "24-hour battery life (89% confidence)\nQuick charge capability (76% confidence)",
      missingFeatures: "Active noise cancellation (73% confidence)\nWireless charging case (68% confidence)",
      keyCompetitors: "Sony WH-1000XM4 ($349) - Premium ANC leader\nBeats Studio3 ($329) - Brand recognition",
      relativeStrengths: "vs Sony WH-1000XM4: Better battery life, more affordable",
      verbatimQuotes: "The battery life on these is absolutely insane - @TechReviewer23",
      relatedSearchTerms: "wireless earbuds long battery (4,200 searches/month)",
      searchOpportunities: "Travel accessories market - position as essential travel tech",
      culturalInsights: "North America: Battery life priority. Europe: Sustainability focus. Asia: Design aesthetics critical.",
      regionalPreferences: "US: 'wireless headphones'. UK: Value focus. Germany: Engineering quality. Japan: Compact design.",
      complianceData: "CE (EU) ✅, FCC (USA) ✅, RoHS ✅, Bluetooth SIG ✅",
      forumDiscussions: "Reddit r/headphones: Battery life praised. r/gaming: Popular for long sessions. r/TravelHacks: Foldable design appreciated.",
      communityInsights: "Tech forums: 'Best battery-to-price ratio'. Audiophile: 'Good entry-level'. Travel: 'Essential item'.",
      influencerReviews: "TechDaily (450K subs): 8.5/10. AudioReviewHub: 4/5 stars. GadgetGuru: 'Recommended'.",
      creatorContent: "23 unboxing videos. Common themes: Premium packaging, solid build, quick setup.",
      videoSentiment: "87% positive. Battery life consistently praised. Value proposition emphasized.",
      technicalSpecs: "40mm drivers, Bluetooth 5.0, 800mAh battery, 20Hz-20kHz response, 32 ohms impedance.",
      performanceBenchmarks: "23.8hrs actual battery (98.3% claimed). Audio quality: 78/100. BT stability: 98.2%.",
      sustainabilityScore: "B+ (78/100). Recyclable packaging. Long lifespan. Energy-efficient charging.",
      environmentalImpact: "12.5kg CO2e per unit. 80% recyclable. RoHS compliant. 90% recycled packaging.",
      compatibleProducts: "Hard case ($19.99), Replacement cushions ($14.99), Backup cable ($9.99), Fast charger ($12.99).",
      ecosystemFit: "Business travel bundle, Gaming starter pack, Remote work setup opportunities.",
      priceHistory: "Launch: $199.99. Current: $189.99. Avg sale: $159.99. Black Friday: $139.99.",
      valuePositioning: "8.2/10 value score. 'Best bang for buck' perception. Sweet spot: $149-179.",
      criticalReviews: "68% want ANC. 23% headband pressure concerns. 18% want app support.",
      featureRequests: "ANC (156 requests), EQ app (89), Multi-device (67), Wireless charging (54).",
      qaInsights: "Top Q: 'Have noise cancellation?' (187 asks). 'Use while charging?' (134 asks).",
      categoryUseCases: "Remote work (35%), Travel (28%), Gaming (22%), Content creation (10%), Fitness (5%).",
      retailerIntelligence: "Amazon: 4.2/5 stars, 'Amazon's Choice'. Best Buy: High associate recommendations.",
      visualPerformance: "Hero image CTR: 4.2%. Lifestyle +32% engagement. Video +67% time on page.",
      expertReviewComparisons: "TechRadar: 4/5. CNET: 7.5/10 'Editor's Choice - Value'. What Hi-Fi: 4/5.",
      innovationGaps: "ANC gap (HIGH impact). Adaptive sound (MEDIUM). Spatial audio (MEDIUM). Wellness features (LOW)."
    },
    {
      id: 2,
      sku: "SM5678",
      name: "SM5678 Smart Fitness Watch",
      brand: "FitTech",
      category: "Electronics > Wearables > Fitness",
      status: "Enriched",
      quality: 88,
      searchTrends: "Growing interest in 'fitness tracker heart rate', 'smartwatch sleep tracking'",
      customerSentiment: "Very positive (4.5/5) - Accuracy praised, battery life questioned",
      socialMentions: "156 mentions/month - fitness influencers recommending",
      competitorAnalysis: "Apple Watch SE ($249), Fitbit Versa 3 ($199) - positioned well at mid-range",
      seoOpportunities: "Rank for 'best budget fitness watch', 'accurate heart rate monitor'",
      targetAudience: "Health-conscious individuals, fitness enthusiasts, age 20-50",
      keyFeatures: "Heart rate monitoring, sleep tracking, 7-day battery, water resistant",
      seoKeywordVolume: "'fitness tracker heart rate' (6,500 searches/month)",
      reasonsToBuy: "1. Accurate heart rate monitoring (91% confidence)\n2. Comprehensive sleep tracking (88% confidence)",
      categoryEntryPoints: "Health Goals & Resolutions: New Year fitness resolution, doctor recommended tracking",
      favouriteFeatures: "Heart rate accuracy (91% confidence)\n7-day battery life (88% confidence)",
      missingFeatures: "GPS tracking (81% confidence)\nMusic storage (65% confidence)",
      keyCompetitors: "Apple Watch SE ($249) - Ecosystem integration\nFitbit Versa 3 ($199) - Health focus leader",
      relativeStrengths: "vs Apple Watch SE: Better battery life, more affordable",
      verbatimQuotes: "Heart rate readings are spot-on compared to my chest strap - FitnessJunkie47",
      relatedSearchTerms: "fitness tracker with heart rate (5,200 searches/month)",
      searchOpportunities: "Fitness motivation content - data-driven progress tracking",
      culturalInsights: "North America: Health tracking priority. Europe: Privacy concerns important. Asia: Fashion + function balance.",
      regionalPreferences: "US: 'fitness tracker'. UK: 'fitness watch'. Germany: Medical-grade accuracy. Japan: Sleek minimalist design.",
      complianceData: "CE (EU) ✅, FCC (USA) ✅, Medical Device Class I (Pending), ISO 13485 ✅",
      forumDiscussions: "r/fitness: Accuracy praised. r/running: GPS lack noted. r/Fitbit: Favorable comparison to Versa.",
      communityInsights: "Fitness forums: 'Best accuracy for price'. Health: 'Reliable tracking'. Tech: 'Great battery life'.",
      influencerReviews: "FitnessTech (320K): 9/10. HealthGadgets: 'Highly recommended'. RunReviewer: 8/10.",
      creatorContent: "18 unboxing videos. Themes: Sleek design, accurate sensors, easy app setup.",
      videoSentiment: "91% positive. Accuracy and battery life top mentions. Some want GPS.",
      technicalSpecs: "PPG heart rate sensor, 3-axis accelerometer, 1.4' AMOLED display, 5ATM water resistant, 300mAh battery.",
      performanceBenchmarks: "Heart rate: ±2 bpm accuracy. Sleep tracking: 94% accuracy vs polysomnography. 7.2 days battery.",
      sustainabilityScore: "B (72/100). Replaceable bands. Long battery cycle. Packaging improvement needed.",
      environmentalImpact: "8.3kg CO2e per unit. 75% recyclable. RoHS compliant. 85% recycled packaging.",
      compatibleProducts: "Extra bands ($24.99), Screen protector ($9.99), Charging dock ($14.99), Chest strap ($39.99).",
      ecosystemFit: "Fitness bundle, Health monitoring package, Wellness ecosystem integration.",
      priceHistory: "Launch: $179.99. Current: $169.99. Avg sale: $149.99. Prime Day: $129.99.",
      valuePositioning: "8.7/10 value score. 'Best accuracy for price' positioning. Sweet spot: $139-159.",
      criticalReviews: "81% want GPS. 15% battery life concerns. 12% want music storage.",
      featureRequests: "GPS tracking (189 requests), Music storage (98), Longer battery (76), SpO2 (54).",
      qaInsights: "Top Q: 'Is it accurate?' (234 asks). 'Works without phone?' (156 asks).",
      categoryUseCases: "Fitness tracking (45%), Sleep monitoring (25%), General health (20%), Sports training (10%).",
      retailerIntelligence: "Amazon: 4.5/5 stars. REI: 'Staff Pick'. Dick's Sporting Goods: High return customer rate.",
      visualPerformance: "Action shots perform best. Health data visualization +45% engagement. Comparison charts +28% conversion.",
      expertReviewComparisons: "Wareable: 4/5. DC Rainmaker: 'Best value fitness tracker'. Tom's Guide: 4.5/5.",
      innovationGaps: "GPS (HIGH impact). Music storage (MEDIUM). Advanced metrics (MEDIUM). Coaching (LOW)."
    },
    {
      id: 3,
      sku: "KB9012",
      name: "KB9012 Mechanical Gaming Keyboard",
      brand: "GamePro",
      category: "Electronics > Gaming > Keyboards",
      status: "Enriched",
      quality: 92,
      searchTrends: "High volume for 'mechanical keyboard RGB', 'gaming keyboard wireless'",
      customerSentiment: "Excellent (4.6/5) - Build quality and responsiveness highlighted",
      socialMentions: "89 mentions/month - esports community endorsements",
      competitorAnalysis: "Razer BlackWidow ($139), Corsair K95 ($199) - competitive features",
      seoOpportunities: "Target 'best mechanical keyboard under $100', 'RGB gaming keyboard'",
      targetAudience: "Gamers, programmers, content creators aged 16-35",
      keyFeatures: "Mechanical switches, RGB backlighting, wireless/wired modes, macro keys",
      seoKeywordVolume: "'mechanical keyboard RGB' (9,800 searches/month)",
      reasonsToBuy: "1. Satisfying mechanical key feel (94% confidence)\n2. Customizable RGB lighting (89% confidence)",
      categoryEntryPoints: "Gaming Performance Needs: Current keyboard too slow for competitive gaming",
      favouriteFeatures: "Mechanical switch feel (94% confidence)\nRGB customization (87% confidence)",
      missingFeatures: "Hot-swappable switches (69% confidence)\nDedicated media controls (64% confidence)",
      keyCompetitors: "Razer BlackWidow V3 ($139) - Brand recognition\nCorsair K95 RGB ($199) - Premium features",
      relativeStrengths: "vs Razer BlackWidow: Better value, dual connectivity",
      verbatimQuotes: "The tactile feedback is perfect for both gaming and coding - CodeWarrior_Dev",
      relatedSearchTerms: "mechanical keyboard for programming (4,800 searches/month)",
      searchOpportunities: "Gaming setup guides - position as essential gaming upgrade",
      culturalInsights: "North America: RGB & performance focus. Europe: Build quality emphasis. Asia: Compact layouts preferred.",
      regionalPreferences: "US: 'mechanical gaming keyboard'. UK: 'RGB keyboard'. Germany: Cherry MX preference. Japan: 60% layouts popular.",
      complianceData: "CE (EU) ✅, FCC (USA) ✅, RoHS ✅, USB-IF Certified ✅",
      forumDiscussions: "r/MechanicalKeyboards: Build quality praised. r/gaming: RGB customization loved. r/programming: Typing experience excellent.",
      communityInsights: "Gaming forums: 'Best switches for price'. Programming: 'Great for coding'. Esports: 'Competitive-ready'.",
      influencerReviews: "LinusTechTips mention. RandomFrankP: 'Budget king'. TechSource: Featured in setup tour.",
      creatorContent: "34 review videos. Themes: Solid construction, satisfying switches, RGB effects impressive.",
      videoSentiment: "92% positive. Switch feel and RGB most praised. Some want hot-swap.",
      technicalSpecs: "Outemu Blue switches, N-key rollover, 1000Hz polling, USB-C + 2.4GHz wireless, Onboard memory.",
      performanceBenchmarks: "1ms response time. 50M keystroke lifespan. 40hr battery (backlight off). Anti-ghosting tested.",
      sustainabilityScore: "C+ (68/100). Durable build extends lifecycle. Keycaps replaceable. Packaging improvement needed.",
      environmentalImpact: "15.2kg CO2e per unit. 70% recyclable. RoHS compliant. 80% recycled packaging.",
      compatibleProducts: "Wrist rest ($19.99), Replacement keycaps ($29.99), Cable ($14.99), Switch puller ($7.99).",
      ecosystemFit: "Gaming setup bundle, Programmer productivity pack, Streamer equipment package.",
      priceHistory: "Launch: $89.99. Current: $79.99. Avg sale: $69.99. Prime Day: $59.99.",
      valuePositioning: "9.1/10 value score. 'Best budget mechanical keyboard'. Sweet spot: $59-79.",
      criticalReviews: "69% want hot-swap switches. 32% want dedicated media keys. 18% software complaints.",
      featureRequests: "Hot-swappable switches (234 requests), Media controls (156), Better software (98), Per-key RGB (87).",
      qaInsights: "Top Q: 'What switches?' (267 asks). 'Works with Mac?' (189 asks). 'Battery life?' (134 asks).",
      categoryUseCases: "Gaming (45%), Programming (30%), General typing (15%), Content creation (10%).",
      retailerIntelligence: "Amazon: 4.6/5 stars, 'Amazon's Choice'. Newegg: 'Editor's Pick'. Micro Center: Top seller.",
      visualPerformance: "RGB showcase videos +85% engagement. Switch sound tests popular. Setup photos drive desire.",
      expertReviewComparisons: "Tom's Hardware: 4/5. PC Gamer: 'Best Budget Pick'. TechRadar: 8/10.",
      innovationGaps: "Hot-swap (HIGH impact). Wireless low-latency (MEDIUM). Per-key RGB (MEDIUM). Analog switches (LOW)."
    }
  ];

  // Generate additional 197 SKUs for table views (IDs 4-200) with real product data
  const additionalProductData = [
    // TVs & Displays (30)
    { id: 4, sku: 'TV5543', name: 'Samsung 55" 4K QLED Smart TV', category: 'Electronics > Displays > Televisions', brand: 'Samsung', quality: 92 },
    { id: 5, sku: 'TV6543', name: 'LG 65" 4K OLED Smart TV', category: 'Electronics > Displays > Televisions', brand: 'LG', quality: 96 },
    { id: 6, sku: 'TV4332', name: 'TCL 43" 4K Roku TV', category: 'Electronics > Displays > Televisions', brand: 'TCL', quality: 85 },
    { id: 7, sku: 'TV7585', name: 'Sony 75" 4K LED Smart TV', category: 'Electronics > Displays > Televisions', brand: 'Sony', quality: 94 },
    { id: 8, sku: 'TV3243', name: 'Hisense 32" HD Smart TV', category: 'Electronics > Displays > Televisions', brand: 'Hisense', quality: 78 },
    { id: 9, sku: 'MON2724', name: 'Dell 27" 4K IPS Monitor', category: 'Electronics > Displays > Monitors', brand: 'Dell', quality: 91 },
    { id: 10, sku: 'MON3227', name: 'ASUS 32" 4K Gaming Monitor 144Hz', category: 'Electronics > Displays > Monitors', brand: 'ASUS', quality: 93 },
    { id: 11, sku: 'MON2427', name: 'ViewSonic 24" Full HD Monitor', category: 'Electronics > Displays > Monitors', brand: 'ViewSonic', quality: 82 },
    { id: 12, sku: 'MON3434', name: 'LG 34" UltraWide Curved Monitor', category: 'Electronics > Displays > Monitors', brand: 'LG', quality: 90 },
    { id: 13, sku: 'TV8585', name: 'Samsung 85" 8K QLED TV', category: 'Electronics > Displays > Televisions', brand: 'Samsung', quality: 97 },
    { id: 14, sku: 'TV5043', name: 'Sony 50" 4K Bravia TV', category: 'Electronics > Displays > Televisions', brand: 'Sony', quality: 89 },
    { id: 15, sku: 'MON2724G', name: 'MSI 27" Gaming Monitor 240Hz', category: 'Electronics > Displays > Monitors', brand: 'MSI', quality: 92 },
    { id: 16, sku: 'TV4350', name: 'Vizio 43" 4K Smart TV', category: 'Electronics > Displays > Televisions', brand: 'Vizio', quality: 84 },
    { id: 17, sku: 'MON1524', name: 'Portable 15.6" USB-C Monitor', category: 'Electronics > Displays > Monitors', brand: 'ASUS', quality: 86 },
    { id: 18, sku: 'PRJ4500', name: '4K Home Theater Projector', category: 'Electronics > Displays > Projectors', brand: 'Epson', quality: 91 },
    { id: 19, sku: 'TV6565', name: 'LG 65" NanoCell 4K TV', category: 'Electronics > Displays > Televisions', brand: 'LG', quality: 90 },
    { id: 20, sku: 'MON2827C', name: 'Samsung 28" 4K Curved Monitor', category: 'Electronics > Displays > Monitors', brand: 'Samsung', quality: 88 },
    { id: 21, sku: 'TV5555', name: 'Hisense 55" ULED 4K TV', category: 'Electronics > Displays > Televisions', brand: 'Hisense', quality: 87 },
    { id: 22, sku: 'MON3227U', name: 'BenQ 32" 4K Designer Monitor', category: 'Electronics > Displays > Monitors', brand: 'BenQ', quality: 93 },
    { id: 23, sku: 'TV7575', name: 'Sony 75" X90K 4K TV', category: 'Electronics > Displays > Televisions', brand: 'Sony', quality: 95 },
    { id: 24, sku: 'MON2424', name: 'HP 24" Full HD Monitor', category: 'Electronics > Displays > Monitors', brand: 'HP', quality: 80 },
    { id: 25, sku: 'TV8577', name: 'Samsung 85" Neo QLED 8K', category: 'Electronics > Displays > Televisions', brand: 'Samsung', quality: 98 },
    { id: 26, sku: 'MON4932', name: 'Samsung 49" Super Ultra Wide', category: 'Electronics > Displays > Monitors', brand: 'Samsung', quality: 94 },
    { id: 27, sku: 'PRJ3000', name: 'Portable Mini Projector', category: 'Electronics > Displays > Projectors', brand: 'Anker', quality: 83 },
    { id: 28, sku: 'TV6060', name: 'TCL 60" 4K QLED TV', category: 'Electronics > Displays > Televisions', brand: 'TCL', quality: 86 },
    { id: 29, sku: 'MON2727P', name: 'Dell 27" QHD Professional Monitor', category: 'Electronics > Displays > Monitors', brand: 'Dell', quality: 90 },
    { id: 30, sku: 'TV4848', name: 'LG 48" OLED C3 TV', category: 'Electronics > Displays > Televisions', brand: 'LG', quality: 96 },
    { id: 31, sku: 'MON3429', name: 'LG 34" UltraWide 5K Monitor', category: 'Electronics > Displays > Monitors', brand: 'LG', quality: 92 },
    { id: 32, sku: 'TV5565', name: 'Vizio 55" OLED 4K TV', category: 'Electronics > Displays > Televisions', brand: 'Vizio', quality: 89 },
    { id: 33, sku: 'PRJ5000', name: 'Laser 4K Projector', category: 'Electronics > Displays > Projectors', brand: 'LG', quality: 93 },

    // Audio (35)
    { id: 34, sku: 'AUD456', name: 'Sony WF-1000XM5 True Wireless Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Sony', quality: 95 },
    { id: 35, sku: 'AUD789', name: 'Bose QuietComfort 45 Headphones', category: 'Electronics > Audio > Headphones', brand: 'Bose', quality: 94 },
    { id: 36, sku: 'AUD234', name: 'Sonos One Smart Speaker', category: 'Electronics > Audio > Smart Speakers', brand: 'Sonos', quality: 93 },
    { id: 37, sku: 'AUD567', name: 'JBL Flip 6 Portable Bluetooth Speaker', category: 'Electronics > Audio > Speakers', brand: 'JBL', quality: 88 },
    { id: 38, sku: 'AUD890', name: 'Sennheiser HD 660S Headphones', category: 'Electronics > Audio > Headphones', brand: 'Sennheiser', quality: 96 },
    { id: 39, sku: 'AUD123', name: 'Beats Studio Buds+ Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Beats', quality: 87 },
    { id: 40, sku: 'AUD345', name: 'Anker Soundcore Life Q30 Headphones', category: 'Electronics > Audio > Headphones', brand: 'Anker', quality: 85 },
    { id: 41, sku: 'AUD678', name: 'Jabra Elite 85t Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Jabra', quality: 91 },
    { id: 42, sku: 'AUD901', name: 'Audio-Technica ATH-M50x Headphones', category: 'Electronics > Audio > Headphones', brand: 'Audio-Technica', quality: 92 },
    { id: 43, sku: 'AUD445', name: 'Bose SoundLink Revolve+ Speaker', category: 'Electronics > Audio > Speakers', brand: 'Bose', quality: 90 },
    { id: 44, sku: 'AUD556', name: 'Sony WH-1000XM5 Headphones', category: 'Electronics > Audio > Headphones', brand: 'Sony', quality: 97 },
    { id: 45, sku: 'AUD667', name: 'JBL Charge 5 Portable Speaker', category: 'Electronics > Audio > Speakers', brand: 'JBL', quality: 89 },
    { id: 46, sku: 'AUD778', name: 'Apple AirPods Pro 2nd Gen', category: 'Electronics > Audio > Earbuds', brand: 'Apple', quality: 95 },
    { id: 47, sku: 'AUD889', name: 'Sonos Arc Soundbar', category: 'Electronics > Audio > Soundbars', brand: 'Sonos', quality: 96 },
    { id: 48, sku: 'AUD990', name: 'Blue Yeti USB Microphone', category: 'Electronics > Audio > Microphones', brand: 'Blue', quality: 90 },
    { id: 49, sku: 'AUD111', name: 'Bose SoundLink Mini II Speaker', category: 'Electronics > Audio > Speakers', brand: 'Bose', quality: 88 },
    { id: 50, sku: 'AUD222', name: 'Samsung Galaxy Buds2 Pro', category: 'Electronics > Audio > Earbuds', brand: 'Samsung', quality: 90 },
    { id: 51, sku: 'AUD333', name: 'Beats Solo3 Wireless Headphones', category: 'Electronics > Audio > Headphones', brand: 'Beats', quality: 86 },
    { id: 52, sku: 'AUD444', name: 'JBL PartyBox 310 Speaker', category: 'Electronics > Audio > Speakers', brand: 'JBL', quality: 87 },
    { id: 53, sku: 'AUD555', name: 'Shure MV7 Podcast Microphone', category: 'Electronics > Audio > Microphones', brand: 'Shure', quality: 93 },
    { id: 54, sku: 'AUD666', name: 'Sonos Beam Soundbar Gen 2', category: 'Electronics > Audio > Soundbars', brand: 'Sonos', quality: 92 },
    { id: 55, sku: 'AUD777', name: 'Anker Soundcore Liberty 4 Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Anker', quality: 86 },
    { id: 56, sku: 'AUD888', name: 'Bose 700 Noise Cancelling Headphones', category: 'Electronics > Audio > Headphones', brand: 'Bose', quality: 94 },
    { id: 57, sku: 'AUD999', name: 'Ultimate Ears BOOM 3 Speaker', category: 'Electronics > Audio > Speakers', brand: 'Ultimate Ears', quality: 87 },
    { id: 58, sku: 'AUD100', name: 'Rode NT-USB Mini Microphone', category: 'Electronics > Audio > Microphones', brand: 'Rode', quality: 88 },
    { id: 59, sku: 'AUD200', name: 'Klipsch The Three II Speaker', category: 'Electronics > Audio > Speakers', brand: 'Klipsch', quality: 91 },
    { id: 60, sku: 'AUD300', name: 'Sennheiser Momentum 4 Wireless', category: 'Electronics > Audio > Headphones', brand: 'Sennheiser', quality: 95 },
    { id: 61, sku: 'AUD400', name: 'Nothing Ear (2) Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Nothing', quality: 85 },
    { id: 62, sku: 'AUD500', name: 'Bose Smart Soundbar 900', category: 'Electronics > Audio > Soundbars', brand: 'Bose', quality: 95 },
    { id: 63, sku: 'AUD600', name: 'Marshall Emberton II Speaker', category: 'Electronics > Audio > Speakers', brand: 'Marshall', quality: 88 },
    { id: 64, sku: 'AUD700', name: 'Sony WF-C700N Earbuds', category: 'Electronics > Audio > Earbuds', brand: 'Sony', quality: 84 },
    { id: 65, sku: 'AUD800', name: 'HyperX Cloud II Gaming Headset', category: 'Electronics > Audio > Headphones', brand: 'HyperX', quality: 87 },
    { id: 66, sku: 'AUD900', name: 'Edifier R1280T Bookshelf Speakers', category: 'Electronics > Audio > Speakers', brand: 'Edifier', quality: 83 },
    { id: 67, sku: 'AUD950', name: 'Elgato Wave:3 Microphone', category: 'Electronics > Audio > Microphones', brand: 'Elgato', quality: 89 },
    { id: 68, sku: 'AUD975', name: 'JBL Bar 5.1 Surround Soundbar', category: 'Electronics > Audio > Soundbars', brand: 'JBL', quality: 90 },

    // Computing (30)
    { id: 69, sku: 'LAP892', name: 'Dell XPS 13 Ultrabook', category: 'Electronics > Computing > Laptops', brand: 'Dell', quality: 94 },
    { id: 70, sku: 'LAP456', name: 'HP Pavilion 15 Laptop', category: 'Electronics > Computing > Laptops', brand: 'HP', quality: 86 },
    { id: 71, sku: 'LAP789', name: 'MacBook Air M2', category: 'Electronics > Computing > Laptops', brand: 'Apple', quality: 97 },
    { id: 72, sku: 'LAP123', name: 'ASUS ROG Zephyrus Gaming Laptop', category: 'Electronics > Computing > Laptops', brand: 'ASUS', quality: 95 },
    { id: 73, sku: 'LAP345', name: 'Lenovo ThinkPad X1 Carbon', category: 'Electronics > Computing > Laptops', brand: 'Lenovo', quality: 93 },
    { id: 74, sku: 'TAB567', name: 'iPad Pro 12.9"', category: 'Electronics > Computing > Tablets', brand: 'Apple', quality: 96 },
    { id: 75, sku: 'TAB890', name: 'Samsung Galaxy Tab S9', category: 'Electronics > Computing > Tablets', brand: 'Samsung', quality: 92 },
    { id: 76, sku: 'TAB234', name: 'Amazon Fire HD 10', category: 'Electronics > Computing > Tablets', brand: 'Amazon', quality: 79 },
    { id: 77, sku: 'KEY456', name: 'Logitech MX Keys Mechanical Keyboard', category: 'Electronics > Computing > Keyboards', brand: 'Logitech', quality: 92 },
    { id: 78, sku: 'KEY789', name: 'Corsair K95 RGB Gaming Keyboard', category: 'Electronics > Computing > Keyboards', brand: 'Corsair', quality: 90 },
    { id: 79, sku: 'KEY123', name: 'Keychron K2 Wireless Mechanical', category: 'Electronics > Computing > Keyboards', brand: 'Keychron', quality: 88 },
    { id: 80, sku: 'MOU456', name: 'Logitech MX Master 3S Mouse', category: 'Electronics > Computing > Mice', brand: 'Logitech', quality: 94 },
    { id: 81, sku: 'MOU789', name: 'Razer DeathAdder V3 Gaming Mouse', category: 'Electronics > Computing > Mice', brand: 'Razer', quality: 91 },
    { id: 82, sku: 'MOU123', name: 'Apple Magic Mouse', category: 'Electronics > Computing > Mice', brand: 'Apple', quality: 85 },
    { id: 83, sku: 'CAM789', name: 'Logitech C920 HD Webcam', category: 'Electronics > Computing > Webcams', brand: 'Logitech', quality: 88 },
    { id: 84, sku: 'CAM345', name: 'Razer Kiyo Pro Ultra 4K Webcam', category: 'Electronics > Computing > Webcams', brand: 'Razer', quality: 93 },
    { id: 85, sku: 'LAP678', name: 'Microsoft Surface Laptop 5', category: 'Electronics > Computing > Laptops', brand: 'Microsoft', quality: 91 },
    { id: 86, sku: 'LAP901', name: 'Acer Swift 3 Laptop', category: 'Electronics > Computing > Laptops', brand: 'Acer', quality: 84 },
    { id: 87, sku: 'TAB678', name: 'Microsoft Surface Pro 9', category: 'Electronics > Computing > Tablets', brand: 'Microsoft', quality: 93 },
    { id: 88, sku: 'TAB901', name: 'Lenovo Tab P11 Pro', category: 'Electronics > Computing > Tablets', brand: 'Lenovo', quality: 87 },
    { id: 89, sku: 'KEY345', name: 'Razer BlackWidow V4 Keyboard', category: 'Electronics > Computing > Keyboards', brand: 'Razer', quality: 89 },
    { id: 90, sku: 'KEY678', name: 'Microsoft Ergonomic Keyboard', category: 'Electronics > Computing > Keyboards', brand: 'Microsoft', quality: 83 },
    { id: 91, sku: 'MOU345', name: 'Logitech G502 HERO Gaming Mouse', category: 'Electronics > Computing > Mice', brand: 'Logitech', quality: 90 },
    { id: 92, sku: 'MOU678', name: 'Microsoft Ergonomic Mouse', category: 'Electronics > Computing > Mice', brand: 'Microsoft', quality: 82 },
    { id: 93, sku: 'CAM567', name: 'Elgato Facecam Pro 4K Webcam', category: 'Electronics > Computing > Webcams', brand: 'Elgato', quality: 92 },
    { id: 94, sku: 'ACC123', name: 'Laptop Stand Aluminum', category: 'Electronics > Computing > Accessories', brand: 'Rain Design', quality: 86 },
    { id: 95, sku: 'ACC456', name: 'USB-C Hub 7-in-1', category: 'Electronics > Computing > Accessories', brand: 'Anker', quality: 87 },
    { id: 96, sku: 'LAP234', name: 'ASUS VivoBook 15', category: 'Electronics > Computing > Laptops', brand: 'ASUS', quality: 82 },
    { id: 97, sku: 'TAB345', name: 'iPad Air 5th Gen', category: 'Electronics > Computing > Tablets', brand: 'Apple', quality: 94 },
    { id: 98, sku: 'MOU901', name: 'Logitech MX Vertical Ergonomic Mouse', category: 'Electronics > Computing > Mice', brand: 'Logitech', quality: 89 },

    // Mobile Accessories (25)
    { id: 99, sku: 'PHN123', name: 'iPhone 15 Pro', category: 'Electronics > Mobile > Smartphones', brand: 'Apple', quality: 97 },
    { id: 100, sku: 'PHN456', name: 'Samsung Galaxy S24 Ultra', category: 'Electronics > Mobile > Smartphones', brand: 'Samsung', quality: 96 },
    { id: 101, sku: 'PHN789', name: 'Google Pixel 8 Pro', category: 'Electronics > Mobile > Smartphones', brand: 'Google', quality: 94 },
    { id: 102, sku: 'CAS123', name: 'OtterBox Defender iPhone Case', category: 'Electronics > Mobile > Cases', brand: 'OtterBox', quality: 90 },
    { id: 103, sku: 'CAS456', name: 'Spigen Ultra Hybrid Case', category: 'Electronics > Mobile > Cases', brand: 'Spigen', quality: 85 },
    { id: 104, sku: 'CAS789', name: 'Apple Silicone iPhone Case', category: 'Electronics > Mobile > Cases', brand: 'Apple', quality: 88 },
    { id: 105, sku: 'SCR123', name: 'Tempered Glass Screen Protector 2-Pack', category: 'Electronics > Mobile > Protection', brand: 'AmFilm', quality: 83 },
    { id: 106, sku: 'PWR123', name: 'Anker PowerCore 20000mAh Power Bank', category: 'Electronics > Mobile > Chargers', brand: 'Anker', quality: 91 },
    { id: 107, sku: 'PWR456', name: 'Anker 30000mAh USB-C Power Bank', category: 'Electronics > Mobile > Chargers', brand: 'Anker', quality: 92 },
    { id: 108, sku: 'PWR789', name: 'Belkin 10000mAh Wireless Power Bank', category: 'Electronics > Mobile > Chargers', brand: 'Belkin', quality: 88 },
    { id: 109, sku: 'CBL123', name: 'USB-C to Lightning Cable 6ft', category: 'Electronics > Mobile > Cables', brand: 'Anker', quality: 86 },
    { id: 110, sku: 'CBL456', name: 'Braided USB-C Cable 3-Pack', category: 'Electronics > Mobile > Cables', brand: 'UGREEN', quality: 84 },
    { id: 111, sku: 'CHG123', name: 'Anker 65W USB-C Wall Charger', category: 'Electronics > Mobile > Chargers', brand: 'Anker', quality: 90 },
    { id: 112, sku: 'CHG456', name: 'Belkin 3-in-1 Wireless Charger', category: 'Electronics > Mobile > Chargers', brand: 'Belkin', quality: 91 },
    { id: 113, sku: 'MNT123', name: 'Magnetic Car Phone Mount', category: 'Electronics > Mobile > Mounts', brand: 'iOttie', quality: 87 },
    { id: 114, sku: 'MNT456', name: 'Dashboard Phone Holder', category: 'Electronics > Mobile > Mounts', brand: 'Mpow', quality: 82 },
    { id: 115, sku: 'PHN234', name: 'OnePlus 12 Smartphone', category: 'Electronics > Mobile > Smartphones', brand: 'OnePlus', quality: 92 },
    { id: 116, sku: 'PHN567', name: 'Xiaomi 13 Pro', category: 'Electronics > Mobile > Smartphones', brand: 'Xiaomi', quality: 91 },
    { id: 117, sku: 'CAS234', name: 'Leather Wallet iPhone Case', category: 'Electronics > Mobile > Cases', brand: 'Bellroy', quality: 89 },
    { id: 118, sku: 'PWR234', name: 'RAVPower 26800mAh Power Bank', category: 'Electronics > Mobile > Chargers', brand: 'RAVPower', quality: 90 },
    { id: 119, sku: 'CHG789', name: 'Apple MagSafe Charger', category: 'Electronics > Mobile > Chargers', brand: 'Apple', quality: 93 },
    { id: 120, sku: 'MNT789', name: 'Adjustable Phone Stand', category: 'Electronics > Mobile > Stands', brand: 'Lamicall', quality: 81 },
    { id: 121, sku: 'CBL789', name: 'Apple USB-C to Lightning Cable', category: 'Electronics > Mobile > Cables', brand: 'Apple', quality: 92 },
    { id: 122, sku: 'CAS567', name: 'Samsung Silicone Case', category: 'Electronics > Mobile > Cases', brand: 'Samsung', quality: 86 },
    { id: 123, sku: 'SCR456', name: 'Privacy Screen Protector', category: 'Electronics > Mobile > Protection', brand: 'ZAGG', quality: 88 },

    // Smart Home (25)
    { id: 124, sku: 'SMT123', name: 'Ring Video Doorbell Pro 2', category: 'Electronics > Smart Home > Doorbells', brand: 'Ring', quality: 92 },
    { id: 125, sku: 'SMT456', name: 'Nest Learning Thermostat', category: 'Electronics > Smart Home > Thermostats', brand: 'Nest', quality: 94 },
    { id: 126, sku: 'SMT789', name: 'Arlo Pro 4 Security Camera 2-Pack', category: 'Electronics > Smart Home > Cameras', brand: 'Arlo', quality: 91 },
    { id: 127, sku: 'SMT234', name: 'Philips Hue White & Color 4-Bulb Starter Kit', category: 'Electronics > Smart Home > Lighting', brand: 'Philips Hue', quality: 93 },
    { id: 128, sku: 'SMT567', name: 'TP-Link Kasa Smart Plug 4-Pack', category: 'Electronics > Smart Home > Plugs', brand: 'TP-Link', quality: 86 },
    { id: 129, sku: 'SMT890', name: 'August Smart Lock Pro', category: 'Electronics > Smart Home > Locks', brand: 'August', quality: 90 },
    { id: 130, sku: 'SMT345', name: 'Wyze Cam v3 Indoor/Outdoor Camera', category: 'Electronics > Smart Home > Cameras', brand: 'Wyze', quality: 84 },
    { id: 131, sku: 'SMT678', name: 'ecobee SmartThermostat Premium', category: 'Electronics > Smart Home > Thermostats', brand: 'ecobee', quality: 93 },
    { id: 132, sku: 'SMT901', name: 'Ring Indoor Cam', category: 'Electronics > Smart Home > Cameras', brand: 'Ring', quality: 85 },
    { id: 133, sku: 'SMT111', name: 'Philips Hue LED Light Strip 6ft', category: 'Electronics > Smart Home > Lighting', brand: 'Philips Hue', quality: 89 },
    { id: 134, sku: 'SMT222', name: 'Samsung SmartThings Hub', category: 'Electronics > Smart Home > Hubs', brand: 'Samsung', quality: 87 },
    { id: 135, sku: 'SMT333', name: 'Lutron Caseta Smart Dimmer Switch', category: 'Electronics > Smart Home > Switches', brand: 'Lutron', quality: 90 },
    { id: 136, sku: 'SMT444', name: 'Ring Alarm 8-piece Security Kit', category: 'Electronics > Smart Home > Security', brand: 'Ring', quality: 91 },
    { id: 137, sku: 'SMT555', name: 'Arlo Essential Video Doorbell', category: 'Electronics > Smart Home > Doorbells', brand: 'Arlo', quality: 88 },
    { id: 138, sku: 'SMT666', name: 'Eve Motion Sensor', category: 'Electronics > Smart Home > Sensors', brand: 'Eve', quality: 83 },
    { id: 139, sku: 'SMT777', name: 'Yale Assure Lock 2', category: 'Electronics > Smart Home > Locks', brand: 'Yale', quality: 92 },
    { id: 140, sku: 'SMT888', name: 'Google Nest Cam Indoor', category: 'Electronics > Smart Home > Cameras', brand: 'Nest', quality: 89 },
    { id: 141, sku: 'SMT999', name: 'Philips Hue Play Light Bar 2-Pack', category: 'Electronics > Smart Home > Lighting', brand: 'Philips Hue', quality: 90 },
    { id: 142, sku: 'SMT100', name: 'TP-Link Tapo Smart Bulb 4-Pack', category: 'Electronics > Smart Home > Lighting', brand: 'TP-Link', quality: 82 },
    { id: 143, sku: 'SMT200', name: 'Ring Floodlight Cam Wired Plus', category: 'Electronics > Smart Home > Cameras', brand: 'Ring', quality: 90 },
    { id: 144, sku: 'SMT300', name: 'Honeywell Home T9 Thermostat', category: 'Electronics > Smart Home > Thermostats', brand: 'Honeywell', quality: 88 },
    { id: 145, sku: 'SMT400', name: 'Kasa Smart Light Switch 3-Way', category: 'Electronics > Smart Home > Switches', brand: 'TP-Link', quality: 85 },
    { id: 146, sku: 'SMT500', name: 'Nest Protect Smoke Detector', category: 'Electronics > Smart Home > Sensors', brand: 'Nest', quality: 91 },
    { id: 147, sku: 'SMT600', name: 'Schlage Encode Smart Lock', category: 'Electronics > Smart Home > Locks', brand: 'Schlage', quality: 93 },
    { id: 148, sku: 'SMT700', name: 'Blink Outdoor 3-Camera System', category: 'Electronics > Smart Home > Cameras', brand: 'Blink', quality: 86 },

    // Gaming (20)
    { id: 149, sku: 'GAM567', name: 'Xbox Series X Console', category: 'Electronics > Gaming > Consoles', brand: 'Microsoft', quality: 96 },
    { id: 150, sku: 'GAM890', name: 'PlayStation 5 Console', category: 'Electronics > Gaming > Consoles', brand: 'Sony', quality: 97 },
    { id: 151, sku: 'GAM123', name: 'Nintendo Switch OLED', category: 'Electronics > Gaming > Consoles', brand: 'Nintendo', quality: 94 },
    { id: 152, sku: 'GAM456', name: 'Xbox Elite Controller Series 2', category: 'Electronics > Gaming > Controllers', brand: 'Microsoft', quality: 93 },
    { id: 153, sku: 'GAM789', name: 'DualSense Wireless Controller', category: 'Electronics > Gaming > Controllers', brand: 'Sony', quality: 91 },
    { id: 154, sku: 'GAM234', name: 'Razer Kraken Gaming Headset', category: 'Electronics > Gaming > Headsets', brand: 'Razer', quality: 88 },
    { id: 155, sku: 'GAM345', name: 'SteelSeries Arctis Nova Pro Wireless', category: 'Electronics > Gaming > Headsets', brand: 'SteelSeries', quality: 95 },
    { id: 156, sku: 'GAM678', name: 'Logitech G923 Racing Wheel', category: 'Electronics > Gaming > Accessories', brand: 'Logitech', quality: 92 },
    { id: 157, sku: 'GAM901', name: 'Razer Wolverine V2 Pro Controller', category: 'Electronics > Gaming > Controllers', brand: 'Razer', quality: 90 },
    { id: 158, sku: 'GAM111', name: 'Meta Quest 3 VR Headset', category: 'Electronics > Gaming > VR', brand: 'Meta', quality: 94 },
    { id: 159, sku: 'GAM222', name: 'HyperX Cloud Alpha Wireless Headset', category: 'Electronics > Gaming > Headsets', brand: 'HyperX', quality: 91 },
    { id: 160, sku: 'GAM333', name: 'Secretlab Titan Evo Gaming Chair', category: 'Electronics > Gaming > Furniture', brand: 'Secretlab', quality: 95 },
    { id: 161, sku: 'GAM444', name: '8BitDo Pro 2 Controller', category: 'Electronics > Gaming > Controllers', brand: '8BitDo', quality: 87 },
    { id: 162, sku: 'GAM555', name: 'Thrustmaster T.Flight HOTAS One', category: 'Electronics > Gaming > Accessories', brand: 'Thrustmaster', quality: 86 },
    { id: 163, sku: 'GAM666', name: 'PlayStation VR2', category: 'Electronics > Gaming > VR', brand: 'Sony', quality: 93 },
    { id: 164, sku: 'GAM777', name: 'Corsair K70 RGB Gaming Keyboard', category: 'Electronics > Gaming > Keyboards', brand: 'Corsair', quality: 90 },
    { id: 165, sku: 'GAM888', name: 'Razer Basilisk V3 Gaming Mouse', category: 'Electronics > Gaming > Mice', brand: 'Razer', quality: 89 },
    { id: 166, sku: 'GAM999', name: 'Elgato Stream Deck', category: 'Electronics > Gaming > Streaming', brand: 'Elgato', quality: 92 },
    { id: 167, sku: 'GAM100', name: 'Nintendo Switch Pro Controller', category: 'Electronics > Gaming > Controllers', brand: 'Nintendo', quality: 90 },
    { id: 168, sku: 'GAM200', name: 'Razer Enki Gaming Chair', category: 'Electronics > Gaming > Furniture', brand: 'Razer', quality: 89 },

    // Wearables (15)
    { id: 169, sku: 'WAT123', name: 'Apple Watch Series 9', category: 'Electronics > Wearables > Smartwatches', brand: 'Apple', quality: 97 },
    { id: 170, sku: 'WAT456', name: 'Samsung Galaxy Watch 6', category: 'Electronics > Wearables > Smartwatches', brand: 'Samsung', quality: 93 },
    { id: 171, sku: 'WAT789', name: 'Fitbit Charge 6', category: 'Electronics > Wearables > Fitness Trackers', brand: 'Fitbit', quality: 89 },
    { id: 172, sku: 'WAT234', name: 'Garmin Forerunner 965', category: 'Electronics > Wearables > Smartwatches', brand: 'Garmin', quality: 95 },
    { id: 173, sku: 'WAT567', name: 'Amazfit GTR 4', category: 'Electronics > Wearables > Smartwatches', brand: 'Amazfit', quality: 87 },
    { id: 174, sku: 'WAT890', name: 'Fitbit Inspire 3', category: 'Electronics > Wearables > Fitness Trackers', brand: 'Fitbit', quality: 85 },
    { id: 175, sku: 'WAT111', name: 'Garmin Venu 3', category: 'Electronics > Wearables > Smartwatches', brand: 'Garmin', quality: 92 },
    { id: 176, sku: 'WAT222', name: 'Whoop 4.0', category: 'Electronics > Wearables > Fitness Trackers', brand: 'Whoop', quality: 90 },
    { id: 177, sku: 'WAT333', name: 'Oura Ring Gen 3', category: 'Electronics > Wearables > Smart Rings', brand: 'Oura', quality: 91 },
    { id: 178, sku: 'WAT444', name: 'Polar Vantage V3', category: 'Electronics > Wearables > Smartwatches', brand: 'Polar', quality: 93 },
    { id: 179, sku: 'WAT555', name: 'Xiaomi Mi Band 8', category: 'Electronics > Wearables > Fitness Trackers', brand: 'Xiaomi', quality: 82 },
    { id: 180, sku: 'WAT666', name: 'Apple Watch Ultra 2', category: 'Electronics > Wearables > Smartwatches', brand: 'Apple', quality: 98 },
    { id: 181, sku: 'WAT777', name: 'Garmin Fenix 7X', category: 'Electronics > Wearables > Smartwatches', brand: 'Garmin', quality: 96 },
    { id: 182, sku: 'WAT888', name: 'Withings ScanWatch', category: 'Electronics > Wearables > Smartwatches', brand: 'Withings', quality: 88 },
    { id: 183, sku: 'WAT999', name: 'Coros Pace 3', category: 'Electronics > Wearables > Smartwatches', brand: 'Coros', quality: 86 },

    // Photography (10)
    { id: 184, sku: 'CAM123', name: 'Sony A7 IV Mirrorless Camera', category: 'Electronics > Photography > Cameras', brand: 'Sony', quality: 96 },
    { id: 185, sku: 'CAM456', name: 'Canon EOS R6 Mark II', category: 'Electronics > Photography > Cameras', brand: 'Canon', quality: 95 },
    { id: 186, sku: 'CAM890', name: 'GoPro HERO12 Black', category: 'Electronics > Photography > Action Cameras', brand: 'GoPro', quality: 92 },
    { id: 187, sku: 'DRN445', name: 'DJI Mini 3 Pro Drone', category: 'Electronics > Photography > Drones', brand: 'DJI', quality: 93 },
    { id: 188, sku: 'DRN678', name: 'DJI Air 3 Drone', category: 'Electronics > Photography > Drones', brand: 'DJI', quality: 94 },
    { id: 189, sku: 'CAM234', name: 'Insta360 X3 Action Camera', category: 'Electronics > Photography > Action Cameras', brand: 'Insta360', quality: 90 },
    { id: 190, sku: 'ACC789', name: 'Manfrotto Carbon Fiber Tripod', category: 'Electronics > Photography > Accessories', brand: 'Manfrotto', quality: 91 },
    { id: 191, sku: 'ACC234', name: 'DJI RS 3 Pro Gimbal', category: 'Electronics > Photography > Gimbals', brand: 'DJI', quality: 93 },
    { id: 192, sku: 'DRN901', name: 'DJI Mavic 3 Classic', category: 'Electronics > Photography > Drones', brand: 'DJI', quality: 95 },
    { id: 193, sku: 'CAM567', name: 'Nikon Z8 Mirrorless Camera', category: 'Electronics > Photography > Cameras', brand: 'Nikon', quality: 97 },

    // Networking (5)
    { id: 194, sku: 'NET678', name: 'TP-Link AX6000 WiFi 6 Router', category: 'Electronics > Networking > Routers', brand: 'TP-Link', quality: 89 },
    { id: 195, sku: 'NET123', name: 'Netgear Orbi WiFi 6E Mesh System', category: 'Electronics > Networking > Mesh Systems', brand: 'Netgear', quality: 93 },
    { id: 196, sku: 'NET456', name: 'ASUS RT-AX88U Gaming Router', category: 'Electronics > Networking > Routers', brand: 'ASUS', quality: 91 },
    { id: 197, sku: 'NET789', name: 'TP-Link RE705X WiFi 6 Range Extender', category: 'Electronics > Networking > Extenders', brand: 'TP-Link', quality: 85 },
    { id: 198, sku: 'NET234', name: 'Google Nest WiFi Pro 6E', category: 'Electronics > Networking > Mesh Systems', brand: 'Google', quality: 90 },

    // Storage (7)
    { id: 199, sku: 'STO901', name: 'Samsung T7 2TB Portable SSD', category: 'Electronics > Storage > SSDs', brand: 'Samsung', quality: 93 },
    { id: 200, sku: 'STO123', name: 'WD My Passport 4TB External HDD', category: 'Electronics > Storage > HDDs', brand: 'Western Digital', quality: 87 }
  ];

  const enrichedAdditional = additionalProductData.map(product => ({
    ...product,
    status: product.quality >= 90 ? 'Enriched' as const : 'Needs Review' as const,
    searchTrends: `Growing demand for ${product.name.toLowerCase()}`,
    customerSentiment: `Positive (${(3.8 + product.quality / 25).toFixed(1)}/5) - Strong customer satisfaction`,
    socialMentions: `${100 + Math.floor(Math.random() * 300)} mentions/month`,
    competitorAnalysis: `Competitive positioning in ${product.category.split(' > ').pop()} market`,
    seoOpportunities: `Target "${product.name.toLowerCase()}" and related long-tail keywords`,
    targetAudience: 'Tech enthusiasts, professionals, consumers seeking quality',
    keyFeatures: 'Premium features, Quality build, Advanced technology',
    seoKeywordVolume: `${Math.floor(Math.random() * 10000) + 1000} searches/month`,
    reasonsToBuy: `Superior ${product.category.split(' > ').pop()?.toLowerCase()} performance and reliability`,
    categoryEntryPoints: 'Product research and comparison phase',
    favouriteFeatures: 'Key feature highlights praised by customers',
    missingFeatures: 'Potential enhancement opportunities identified',
    keyCompetitors: `Major ${product.brand} competitors in segment`,
    relativeStrengths: 'Competitive advantages in quality and value',
    verbatimQuotes: `"Excellent ${product.category.split(' > ').pop()?.toLowerCase()}" - Verified Customer`,
    relatedSearchTerms: `Related ${product.category.split(' > ').pop()?.toLowerCase()} searches`,
    searchOpportunities: `Strong market positioning for ${product.brand} products`,
    culturalInsights: 'Regional market insights available',
    regionalPreferences: 'Geographic preferences analyzed',
    complianceData: 'CE, FCC, RoHS certified',
    forumDiscussions: 'Positive community discussions',
    communityInsights: 'Strong community sentiment',
    influencerReviews: 'Favorable influencer coverage',
    creatorContent: 'Active creator engagement',
    videoSentiment: `${75 + Math.floor(Math.random() * 20)}% positive sentiment`,
    technicalSpecs: 'Premium specifications',
    performanceBenchmarks: 'Strong performance metrics',
    sustainabilityScore: 'B+ environmental rating',
    environmentalImpact: 'Sustainable manufacturing practices',
    compatibleProducts: 'Ecosystem compatibility available',
    ecosystemFit: 'Product ecosystem integration',
    priceHistory: 'Stable pricing trends',
    valuePositioning: 'Strong value proposition',
    criticalReviews: 'Constructive feedback addressed',
    featureRequests: 'Customer enhancement requests tracked',
    qaInsights: 'Common questions addressed in FAQ',
    categoryUseCases: `Multiple ${product.category.split(' > ').pop()?.toLowerCase()} use cases supported`,
    retailerIntelligence: 'Strong retailer performance',
    visualPerformance: 'High visual engagement in marketing',
    expertReviewComparisons: 'Favorable expert reviews',
    innovationGaps: 'Innovation opportunities identified'
  }));

  return [...baseAssets, ...enrichedAdditional];
};